In [1]:
import cv2
import numpy as np

## ---------------------------------------------------------------------------------------------------------------------------------

# Image Arithmetic

## Images can be Added and Subtracted together.

### We can also define Image Arithmetic as simple Matrix Addition(with extra caveats) as Image are just NUMPY Matrix.

### There are mainly 2 ways to perform Image Arithmetic Operations :-

### 1)First way is to use OpenCV Specfic Functions.
### 2)Second way is using Numpy Basic Addition and Subtraction operators.

## We will be using the OpenCV Functions as they will perform Clipping or Saturation which will ensure Pixel Intensity never falls outside of range [0,255]. 

#### ---------------------------------------------------------------------------------------------------------------

## --->Image Addition

### We use `cv2.add()` Method to perform Image Addition in OpenCV.(It perform Clipping or Saturation under the hood).

### For `cv2.add()` Method:-

### < First Argument >:-It takes the Numpy Array of the First Image we want to Add.
### < Second Argument >:-It takes the Numpy Array of the Second Image we want to Add.
### < Third Argument >(mask) :- It is Optional Operation Mask we can use to alter the output Image.

#### cv2.add():-[LINK](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga10ac1bfb180e2cfda1701d06c24fdbd6)

In [2]:
img1 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\adrian.png")
img2 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\opencv.png")

In [3]:
cv2.imshow("Image1",img1)
cv2.imshow("Image2",img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
img1.shape

(450, 600, 3)

In [5]:
img2.shape

(554, 450, 3)

In [6]:
Rimg1 = cv2.resize(img1,(600,600),cv2.INTER_CUBIC)
Rimg2 = cv2.resize(img2,(600,600),cv2.INTER_CUBIC)

In [7]:
add12 = cv2.add(Rimg1,Rimg2)

In [8]:
add21 = cv2.add(Rimg2,Rimg1)

In [9]:
cv2.imshow("Image1",Rimg1)
cv2.imshow("Image2",Rimg2)
cv2.imshow("Added12",add12)
cv2.imshow("Added21",add21)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We have Performed Image Addition of two Images to obtain an Final Output Image.

### We can Notice that Clipping and Saturation were performed Under the Hood.

### -->We will Perform Basic Image Addition in below Cells.

### -->Basic Image Addition is Adding some constant value to each Pixel ,Thus Increasing the Contrast ,Brightness of the Image.

In [10]:
img3 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\grand_canyon.png")

In [16]:
img3

array([[[115,  73,   4],
        [115,  73,   3],
        [116,  74,   3],
        ...,
        [112,  71,   7],
        [118,  80,  20],
        [121,  87,  35]],

       [[113,  72,   2],
        [115,  73,   1],
        [118,  76,   6],
        ...,
        [116,  74,  10],
        [119,  80,  22],
        [121,  86,  33]],

       [[114,  72,   2],
        [116,  73,   3],
        [119,  75,   4],
        ...,
        [112,  70,   4],
        [114,  75,  13],
        [119,  83,  28]],

       ...,

       [[  0,   7,   4],
        [  5,   0,   0],
        [ 11,  77, 105],
        ...,
        [ 51, 114, 183],
        [ 48, 113, 181],
        [ 51, 119, 188]],

       [[  2,  24,  23],
        [  3,  69,  81],
        [  3, 108, 141],
        ...,
        [ 54, 127, 198],
        [ 44, 110, 179],
        [ 46, 110, 178]],

       [[  3,  53,  65],
        [  0, 117, 139],
        [  3, 114, 146],
        ...,
        [ 53, 129, 203],
        [ 54, 126, 198],
        [ 53, 120, 188]]

In [11]:
cv2.imshow("Normal Image",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
add100 = cv2.add(img3,100)

In [15]:
add100

array([[[215,  73,   4],
        [215,  73,   3],
        [216,  74,   3],
        ...,
        [212,  71,   7],
        [218,  80,  20],
        [221,  87,  35]],

       [[213,  72,   2],
        [215,  73,   1],
        [218,  76,   6],
        ...,
        [216,  74,  10],
        [219,  80,  22],
        [221,  86,  33]],

       [[214,  72,   2],
        [216,  73,   3],
        [219,  75,   4],
        ...,
        [212,  70,   4],
        [214,  75,  13],
        [219,  83,  28]],

       ...,

       [[100,   7,   4],
        [105,   0,   0],
        [111,  77, 105],
        ...,
        [151, 114, 183],
        [148, 113, 181],
        [151, 119, 188]],

       [[102,  24,  23],
        [103,  69,  81],
        [103, 108, 141],
        ...,
        [154, 127, 198],
        [144, 110, 179],
        [146, 110, 178]],

       [[103,  53,  65],
        [100, 117, 139],
        [103, 114, 146],
        ...,
        [153, 129, 203],
        [154, 126, 198],
        [153, 120, 188]]

In [17]:
addM100 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*100)

In [18]:
addM100

array([[[215, 173, 104],
        [215, 173, 103],
        [216, 174, 103],
        ...,
        [212, 171, 107],
        [218, 180, 120],
        [221, 187, 135]],

       [[213, 172, 102],
        [215, 173, 101],
        [218, 176, 106],
        ...,
        [216, 174, 110],
        [219, 180, 122],
        [221, 186, 133]],

       [[214, 172, 102],
        [216, 173, 103],
        [219, 175, 104],
        ...,
        [212, 170, 104],
        [214, 175, 113],
        [219, 183, 128]],

       ...,

       [[100, 107, 104],
        [105, 100, 100],
        [111, 177, 205],
        ...,
        [151, 214, 255],
        [148, 213, 255],
        [151, 219, 255]],

       [[102, 124, 123],
        [103, 169, 181],
        [103, 208, 241],
        ...,
        [154, 227, 255],
        [144, 210, 255],
        [146, 210, 255]],

       [[103, 153, 165],
        [100, 217, 239],
        [103, 214, 246],
        ...,
        [153, 229, 255],
        [154, 226, 255],
        [153, 220, 255]]

In [19]:
cv2.imshow("Normal Image",img3)
cv2.imshow("Add100",add100)
cv2.imshow("AddM100",addM100)
cv2.waitKey(0)
cv2.destroyAllWindows()

### -->We can notice in the First Method when we Add with just a Constant Value ,It will only Add it to a Single Channel(First Channel(B Channel))  

### -->We can notice in the Second Method when we Add with a Matrix containing each Element as a Constant Value and same shape as the image  ,It will work Properly and Add to all Channel thus Increasing the Brightness and Contrast.

In [20]:
addM25 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*25)
addM50 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*50)
addM75 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*75)
addM100 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*100)
addM125 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*125)
addM150 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*150)
addM175 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*175)
addM200 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*200)
addM225 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*225)
addM250 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*250)
addM255 = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*255)

In [21]:
cv2.imshow("Normal Image",img3)
cv2.imshow("AddM25",addM25)
cv2.imshow("AddM50",addM50)
cv2.imshow("AddM75",addM75)
cv2.imshow("AddM100",addM100)
cv2.imshow("AddM125",addM125)
cv2.imshow("AddM150",addM150)
cv2.imshow("AddM175",addM175)
cv2.imshow("AddM200",addM200)
cv2.imshow("AddM225",addM225)
cv2.imshow("AddM250",addM250)
cv2.imshow("AddM255",addM255)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We can see in above cells ,that we used different Values to Add to the Image to increase Brightness.

In [38]:
# Creating a Mask using cv2.threshold() method

msk = cv2.threshold(cv2.cvtColor(img3,cv2.COLOR_BGR2GRAY),150,255,cv2.THRESH_BINARY)

In [39]:
addimg = cv2.add(img3,np.ones(img3.shape,dtype=np.uint8)*50,mask=msk[1])

In [40]:
cv2.imshow("Normal Image",img3)
cv2.imshow("Added mask Image",addimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We can see that we used the Mask Argument in Add Method in Above Cells.

### In the Above Scenario:-

### 1)The Image was Added the way we wanted.
### 2)Then The Mask was applied on the Added Image,hence only displaying those pixels of Added Image that had 1(True) Corresponding  Pixel in the Mask.
### 3)Hence the Final Output was Generated.

#### ---------------------------------------------------------------------------------------------------------------

## -->Image Subtraction

### To subtract the Images in OpenCV we use `cv2.subtract()` Method.

#### cv2.subtract():-[LINK](https://docs.opencv.org/4.x/d2/de8/group__core__array.html#gaa0f00d98b4b5edeaeb7b8333b2de353b)

In [22]:
subimg12 = cv2.subtract(Rimg1,Rimg2)
subimg21 = cv2.subtract(Rimg2,Rimg1)

In [23]:
cv2.imshow("Sub12",subimg12)
cv2.imshow("Sub21",subimg21)
cv2.waitKey(0)
cv2.destroyAllWindows()

### -->We performed Subtraction Between 2 Images in above Cells.

### -->We can observe that Subtraction is a Commutative Operation because of its Nature.

In [24]:
sub100 = cv2.subtract(img3,100)
subM100 = cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*100)

In [25]:
sub100

array([[[ 15,  73,   4],
        [ 15,  73,   3],
        [ 16,  74,   3],
        ...,
        [ 12,  71,   7],
        [ 18,  80,  20],
        [ 21,  87,  35]],

       [[ 13,  72,   2],
        [ 15,  73,   1],
        [ 18,  76,   6],
        ...,
        [ 16,  74,  10],
        [ 19,  80,  22],
        [ 21,  86,  33]],

       [[ 14,  72,   2],
        [ 16,  73,   3],
        [ 19,  75,   4],
        ...,
        [ 12,  70,   4],
        [ 14,  75,  13],
        [ 19,  83,  28]],

       ...,

       [[  0,   7,   4],
        [  0,   0,   0],
        [  0,  77, 105],
        ...,
        [  0, 114, 183],
        [  0, 113, 181],
        [  0, 119, 188]],

       [[  0,  24,  23],
        [  0,  69,  81],
        [  0, 108, 141],
        ...,
        [  0, 127, 198],
        [  0, 110, 179],
        [  0, 110, 178]],

       [[  0,  53,  65],
        [  0, 117, 139],
        [  0, 114, 146],
        ...,
        [  0, 129, 203],
        [  0, 126, 198],
        [  0, 120, 188]]

In [26]:
subM100

array([[[ 15,   0,   0],
        [ 15,   0,   0],
        [ 16,   0,   0],
        ...,
        [ 12,   0,   0],
        [ 18,   0,   0],
        [ 21,   0,   0]],

       [[ 13,   0,   0],
        [ 15,   0,   0],
        [ 18,   0,   0],
        ...,
        [ 16,   0,   0],
        [ 19,   0,   0],
        [ 21,   0,   0]],

       [[ 14,   0,   0],
        [ 16,   0,   0],
        [ 19,   0,   0],
        ...,
        [ 12,   0,   0],
        [ 14,   0,   0],
        [ 19,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   5],
        ...,
        [  0,  14,  83],
        [  0,  13,  81],
        [  0,  19,  88]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   8,  41],
        ...,
        [  0,  27,  98],
        [  0,  10,  79],
        [  0,  10,  78]],

       [[  0,   0,   0],
        [  0,  17,  39],
        [  0,  14,  46],
        ...,
        [  0,  29, 103],
        [  0,  26,  98],
        [  0,  20,  88]]

### We can see that Like in Addition same happens in Subtraction.

### Hence We can say that to Decrease Brightness we should Subtract from a Matrix of same size containing Same Elements as the Constant Value.

In [27]:
sub255 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*255)
sub250 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*250)
sub225 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*225)
sub200 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*200)
sub175 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*175)
sub150 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*150)
sub125 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*125)
sub100 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*100)
sub75 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*75)
sub50 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*50)
sub25 =  cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*25)

In [29]:
cv2.imshow("Normal Image",img3)
cv2.imshow("Sub255",sub255)
cv2.imshow("Sub250",sub250)
cv2.imshow("Sub225",sub225)
cv2.imshow("Sub200",sub200)
cv2.imshow("Sub175",sub175)
cv2.imshow("Sub150",sub150)
cv2.imshow("Sub125",sub125)
cv2.imshow("Sub100",sub100)
cv2.imshow("Sub75",sub75)
cv2.imshow("Sub50",sub50)
cv2.imshow("Sub25",sub25)
cv2.waitKey(0)
cv2.destroyAllWindows()

### In above Cells we can see that we used Different Values to Subtract From the Image and Obverse it.

In [41]:
msk = cv2.threshold(cv2.cvtColor(img3,cv2.COLOR_BGR2GRAY),150,255,cv2.THRESH_BINARY_INV)

In [43]:
submsk = cv2.subtract(img3,np.ones(img3.shape,dtype=np.uint8)*40,mask=msk[1])

In [44]:
cv2.imshow("Normal Image",img3)
cv2.imshow("Subtracted Masked Images",submsk)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We used the Mask Argument in cv2.subtract() Method and Observe the Output.

### Its working was same the Addition Masking Operation(described Above).

#### ---------------------------------------------------------------------------------------------------------------

## Image Weighted Addition

### To perform Weighted Addition of Images using `cv2.addWeighted()`.

### For `cv2.addWeighted()` Method:-

### < First Argument > :-It takes the NUMPY Array of the First Image we want to Add.
### < Second Argument >:-It takes the Weight of the First Image.It defines the amount by which the First Image Pixels will be used to define the Output Image.
### < Third Argument >:-It takes the NUMPY Array of the Second Image we want to Add.
### < Fourth Argument >:-It takes the Weight of the Second Image.It defines the amount by which the Second Image Pixels will be used to define the Output Image.
### < Fifth Argument >:-It the scalar that will be added to each Input Array.

In [48]:
wimg = cv2.addWeighted(Rimg1,0.5,Rimg2,0.5,0)

In [49]:
cv2.imshow("Added Weighted Image",wimg)
cv2.imshow("Added Image",add21)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We can see that we gave Half Weightage to both Input Images and Obtain an Result which can be observed. 

In [50]:
wimg1 = cv2.addWeighted(Rimg1,1,Rimg2,1,0)

In [51]:
cv2.imshow("Added Weighted Image",wimg1)
cv2.imshow("Added Image",add21)
cv2.waitKey(0)
cv2.destroyAllWindows()

### We can see that we gave full(1) Weightage to both Input Images and Obtain an Result which can be observed.

### This Ouput Image is Same as Normal Addition Image.