In [1]:
import numpy as np

# Creating Numpy Array's

## 1)Creating using `np.array()`

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
type(b)

numpy.ndarray

In [6]:
c = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              
              [[2,4,6,8],
               [10,12,14,16],
               [3,5,7,9]],
              
              [[11,22,33,44],
               [111,222,333,444],
               [1111,2222,3333,4444]]])

c

array([[[   1,    2,    3,    4],
        [   5,    6,    7,    8],
        [   9,   10,   11,   12]],

       [[   2,    4,    6,    8],
        [  10,   12,   14,   16],
        [   3,    5,    7,    9]],

       [[  11,   22,   33,   44],
        [ 111,  222,  333,  444],
        [1111, 2222, 3333, 4444]]])

In [7]:
type(c)

numpy.ndarray

In [8]:
d = np.array([[[1,2,3,4],
               [5,6,7,8]],
              
              [[2,4,6,8],
               [10,12,14,16],
               [3,5,7,9]],
              
              [[11,22,33],
               [111,222,333],
               [1111,2222,3333]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [9]:
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('int32')

In [11]:
c.dtype

dtype('int32')

In [12]:
e = np.array([1,2,3.0,True,"abc"])
e

array(['1', '2', '3.0', 'True', 'abc'], dtype='<U32')

In [13]:
f = np.array([1,2,3,4,5,6,7,8,9,10],dtype = np.float32 )
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [14]:
g = np.array((1,2,3,4,5,6),ndmin=2)
g

array([[1, 2, 3, 4, 5, 6]])

In [15]:
h = np.array({1,2,3,4,5,6,6,7,8})
h

array({1, 2, 3, 4, 5, 6, 7, 8}, dtype=object)

In [16]:
h[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [17]:
i = np.array({'a':1,'b':2,'c':3,'d':4})
i

array({'a': 1, 'b': 2, 'c': 3, 'd': 4}, dtype=object)

In [18]:
i[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [19]:
j = np.array({'a':1,'b':2,'c':3,'d':4},ndmin=1)
j

array([{'a': 1, 'b': 2, 'c': 3, 'd': 4}], dtype=object)

In [20]:
j[0]

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

## 2)Creating using `np.ones()`

In [21]:
on1 = np.ones(3)
on1

array([1., 1., 1.])

In [22]:
on2 = np.ones((3,4))
on2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
on3 = np.ones([2,4,4])
on3

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
on4 = np.ones({4,5})
on4

TypeError: expected a sequence of integers or a single integer, got '{4, 5}'

In [25]:
on5 = np.ones([2,5],dtype=np.int32)
on5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
on6 = np.ones([2,3,4],dtype=bool)
on6

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

## 3)Creating Array using `np.zeros()`

In [27]:
ze1 = np.zeros(4)
ze1

array([0., 0., 0., 0.])

In [28]:
ze2 = np.zeros((3,5))
ze2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
ze3 = np.zeros([3,5,3])
ze3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
ze4 = np.zeros({2,4})
ze4

TypeError: expected a sequence of integers or a single integer, got '{2, 4}'

In [31]:
ze5 = np.zeros((2,4),dtype=np.int32)
ze5

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## 4)Creating Using `np.arange()`

In [32]:
ar1 = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
ar2 = np.arange(10.0)
ar2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
ar3 = np.arange(start=3,stop=15)
ar3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
ar4 = np.arange(start=4,stop=14,step=3)
ar4

array([ 4,  7, 10, 13])

In [36]:
ar5 = np.arange(start=-1,stop=-10,step=-1)
ar5

array([-1, -2, -3, -4, -5, -6, -7, -8, -9])

In [37]:
ar6 = np.arange(start=0.5,stop=3.5,step=0.5)
ar6

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [38]:
ar7 = np.arange(start=10,stop=100,step=10,dtype=np.float32)
ar7

array([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=float32)

In [39]:
ar8 = np.arange(start=1,stop=10,step=10)
ar8

array([1])

In [40]:
ar9 = np.arange(0.4,5,0.25)
ar9

array([0.4 , 0.65, 0.9 , 1.15, 1.4 , 1.65, 1.9 , 2.15, 2.4 , 2.65, 2.9 ,
       3.15, 3.4 , 3.65, 3.9 , 4.15, 4.4 , 4.65, 4.9 ])

In [41]:
ar10 = np.arange(4,1)
ar10

array([], dtype=int32)

In [42]:
ar11 = np.arange(start=0,stop=5,step=0.5, dtype=int)
ar11

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
ar12 = np.arange(start=-3,stop=3,step=0.5, dtype=int)
ar12

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [44]:
ar13 = np.arange(start=10,stop=1)
ar13

array([], dtype=int32)

## 5)Creating Using `np.linespace()`

In [45]:
ln1 = np.linspace(start=1,stop=20,num=20)
ln1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [46]:
ln2 = np.linspace(start=1,stop=20,num=20,endpoint=False)
ln2

array([ 1.  ,  1.95,  2.9 ,  3.85,  4.8 ,  5.75,  6.7 ,  7.65,  8.6 ,
        9.55, 10.5 , 11.45, 12.4 , 13.35, 14.3 , 15.25, 16.2 , 17.15,
       18.1 , 19.05])

In [47]:
ln3 = np.linspace(start=1,stop=20,num=20,dtype=np.int32)
ln3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
ln4 = np.linspace(start=67,stop=60,num=10)
ln4

array([67.        , 66.22222222, 65.44444444, 64.66666667, 63.88888889,
       63.11111111, 62.33333333, 61.55555556, 60.77777778, 60.        ])

In [49]:
ln5 = np.linspace(start=-1,stop=-10,num=5)
ln5

array([ -1.  ,  -3.25,  -5.5 ,  -7.75, -10.  ])

In [50]:
ln6 = np.linspace(start=0.5,stop=15.7,num=12)
ln6

array([ 0.5       ,  1.88181818,  3.26363636,  4.64545455,  6.02727273,
        7.40909091,  8.79090909, 10.17272727, 11.55454545, 12.93636364,
       14.31818182, 15.7       ])

In [51]:
ln7 = np.linspace(1,20,5)
ln7

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [52]:
ln8 = np.linspace(start=[10,20,30,40],stop=100,num=10)
ln8

array([[ 10.        ,  20.        ,  30.        ,  40.        ],
       [ 20.        ,  28.88888889,  37.77777778,  46.66666667],
       [ 30.        ,  37.77777778,  45.55555556,  53.33333333],
       [ 40.        ,  46.66666667,  53.33333333,  60.        ],
       [ 50.        ,  55.55555556,  61.11111111,  66.66666667],
       [ 60.        ,  64.44444444,  68.88888889,  73.33333333],
       [ 70.        ,  73.33333333,  76.66666667,  80.        ],
       [ 80.        ,  82.22222222,  84.44444444,  86.66666667],
       [ 90.        ,  91.11111111,  92.22222222,  93.33333333],
       [100.        , 100.        , 100.        , 100.        ]])

In [53]:
ln9 = np.linspace(start=[10,20,30,40],stop=100,num=10,axis=1)
ln9

array([[ 10.        ,  20.        ,  30.        ,  40.        ,
         50.        ,  60.        ,  70.        ,  80.        ,
         90.        , 100.        ],
       [ 20.        ,  28.88888889,  37.77777778,  46.66666667,
         55.55555556,  64.44444444,  73.33333333,  82.22222222,
         91.11111111, 100.        ],
       [ 30.        ,  37.77777778,  45.55555556,  53.33333333,
         61.11111111,  68.88888889,  76.66666667,  84.44444444,
         92.22222222, 100.        ],
       [ 40.        ,  46.66666667,  53.33333333,  60.        ,
         66.66666667,  73.33333333,  80.        ,  86.66666667,
         93.33333333, 100.        ]])

In [54]:
ln10 = np.linspace(start=[10,20,30,40],stop=[100,110,120,130],num=10)
ln10

array([[ 10.,  20.,  30.,  40.],
       [ 20.,  30.,  40.,  50.],
       [ 30.,  40.,  50.,  60.],
       [ 40.,  50.,  60.,  70.],
       [ 50.,  60.,  70.,  80.],
       [ 60.,  70.,  80.,  90.],
       [ 70.,  80.,  90., 100.],
       [ 80.,  90., 100., 110.],
       [ 90., 100., 110., 120.],
       [100., 110., 120., 130.]])

In [55]:
ln11 = np.linspace(start=[10,20,30,40],stop=[100,110,120,130],num=10,axis=1,dtype=np.int32)
ln11

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [ 30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 40,  50,  60,  70,  80,  90, 100, 110, 120, 130]])

In [56]:
ln12 = np.linspace(start=[10,20,30,40],stop=100,num=10,retstep=True)
ln12

(array([[ 10.        ,  20.        ,  30.        ,  40.        ],
        [ 20.        ,  28.88888889,  37.77777778,  46.66666667],
        [ 30.        ,  37.77777778,  45.55555556,  53.33333333],
        [ 40.        ,  46.66666667,  53.33333333,  60.        ],
        [ 50.        ,  55.55555556,  61.11111111,  66.66666667],
        [ 60.        ,  64.44444444,  68.88888889,  73.33333333],
        [ 70.        ,  73.33333333,  76.66666667,  80.        ],
        [ 80.        ,  82.22222222,  84.44444444,  86.66666667],
        [ 90.        ,  91.11111111,  92.22222222,  93.33333333],
        [100.        , 100.        , 100.        , 100.        ]]),
 array([10.        ,  8.88888889,  7.77777778,  6.66666667]))

In [57]:
ln13 = np.linspace(start=[[1,2,3],[4,5,6]],stop=[[10,20,30],[40,50,60]],num=10)
ln13

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 2.,  4.,  6.],
        [ 8., 10., 12.]],

       [[ 3.,  6.,  9.],
        [12., 15., 18.]],

       [[ 4.,  8., 12.],
        [16., 20., 24.]],

       [[ 5., 10., 15.],
        [20., 25., 30.]],

       [[ 6., 12., 18.],
        [24., 30., 36.]],

       [[ 7., 14., 21.],
        [28., 35., 42.]],

       [[ 8., 16., 24.],
        [32., 40., 48.]],

       [[ 9., 18., 27.],
        [36., 45., 54.]],

       [[10., 20., 30.],
        [40., 50., 60.]]])

In [58]:
ln14 = np.linspace(start=[[1,2,3],[4,5,6]],stop=[[10,20,30],[40,50,60]],num=10,axis=1)
ln14

array([[[ 1.,  2.,  3.],
        [ 2.,  4.,  6.],
        [ 3.,  6.,  9.],
        [ 4.,  8., 12.],
        [ 5., 10., 15.],
        [ 6., 12., 18.],
        [ 7., 14., 21.],
        [ 8., 16., 24.],
        [ 9., 18., 27.],
        [10., 20., 30.]],

       [[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.],
        [16., 20., 24.],
        [20., 25., 30.],
        [24., 30., 36.],
        [28., 35., 42.],
        [32., 40., 48.],
        [36., 45., 54.],
        [40., 50., 60.]]])

In [59]:
ln15 = np.linspace(start=[[1,2,3],[4,5,6]],stop=[[10,20,30],[40,50,60]],num=10,axis=2)
ln15

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
        [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]],

       [[ 4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.],
        [ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.],
        [ 6., 12., 18., 24., 30., 36., 42., 48., 54., 60.]]])

## 6)Creating using `np.random.randint()`

In [60]:
np.random.seed(1)
rin1 = np.random.randint(1,10,size=7)
rin1

array([6, 9, 6, 1, 1, 2, 8])

In [61]:
np.random.seed(5)
rin2 = np.random.randint(low=10,high=20,size=(2,4))
rin2

array([[13, 16, 16, 10],
       [19, 18, 14, 17]])

In [62]:
np.random.seed(1)
rin3 = np.random.randint(low=20,high=30,size=(3,3,4))
rin3

array([[[25, 28, 29, 25],
        [20, 20, 21, 27],
        [26, 29, 22, 24]],

       [[25, 22, 24, 22],
        [24, 27, 27, 29],
        [21, 27, 20, 26]],

       [[29, 29, 27, 26],
        [29, 21, 20, 21],
        [28, 28, 23, 29]]])

In [63]:
np.random.seed(2)
rin4 = np.random.randint(1,4,(2,4))
rin4

array([[1, 2, 1, 3],
       [3, 1, 3, 2]])

In [64]:
np.random.seed(4)
rin5 = np.random.randint(0,40)
rin5

5

In [65]:
np.random.seed(1)
rin6 = np.random.randint(5,size=(4,5))
rin6

array([[3, 4, 0, 1, 3],
       [0, 0, 1, 4, 4],
       [1, 2, 4, 2, 4],
       [3, 4, 2, 4, 2]])

In [66]:
np.random.seed(1)
rin7 = np.random.randint(low=10,size=[3,7])
rin7

array([[5, 8, 9, 5, 0, 0, 1],
       [7, 6, 9, 2, 4, 5, 2],
       [4, 2, 4, 7, 7, 9, 1]])

In [67]:
rin8 = np.random.randint(0,size=7)

ValueError: high <= 0

In [68]:
rin9 = np.random.randint(low=5,high=1,size=(2,3))

ValueError: low >= high

In [69]:
np.random.seed(1)
rin10 = np.random.randint(low=1.5,high=7.9,size=(2,4))
rin10

array([[6, 4, 5, 1],
       [2, 4, 6, 1]])

In [70]:
np.random.seed(1)
rin11 = np.random.randint(low=-6,high=-2,size=(1,3,8))
rin11

array([[[-5, -3, -6, -6, -3, -5, -3, -5],
        [-3, -6, -6, -5, -6, -3, -5, -6],
        [-4, -5, -4, -6, -4, -5, -4, -6]]])

In [71]:
rin12 = np.random.randint(low=[1,2,3,4,5],high=10)
rin12

array([3, 6, 4, 5, 5])

In [72]:
rin13 = np.random.randint(low=3,high=[4,5,6,7,8,9,10])
rin13

array([3, 3, 4, 4, 4, 8, 9])

In [73]:
rin14 = np.random.randint(low=3,high=[4,5,6,7,8,9,10],size=(2,4))

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 1 with shape (7,) and arg 2 with shape (2, 4).

In [74]:
rin15 = np.random.randint(low=[1,2,3,4,5],high=[7,8,9,10,11])
rin15

array([2, 3, 3, 8, 6])

In [75]:
rin16 = np.random.randint(low=[1,2,3,4],high=[11,12])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## 7)Creating using `np.random.random()`

In [76]:
np.random.seed(100)
rrn1 = np.random.random(7)
rrn1

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908])

In [77]:
np.random.seed(110)
rrn2 = np.random.random([3,4])
rrn2

array([[0.11605886, 0.65845538, 0.37558898, 0.61278258],
       [0.67949055, 0.68246313, 0.95501   , 0.63722294],
       [0.51294361, 0.08617633, 0.38746845, 0.29044365]])

In [78]:
np.random.random(120)
rrn3 = np.random.random((2,3,5))
rrn3

array([[[0.78562563, 0.72298581, 0.92110921, 0.24929446, 0.53187711],
        [0.0770701 , 0.86865633, 0.9451499 , 0.29593616, 0.00190572],
        [0.90469584, 0.3191481 , 0.02951962, 0.18681647, 0.45073758]],

       [[0.30582518, 0.01979762, 0.88265423, 0.14936613, 0.78989321],
        [0.98599239, 0.75689422, 0.60701891, 0.89809489, 0.0706648 ],
        [0.94690936, 0.87341823, 0.31277174, 0.04470116, 0.20160189]]])

In [79]:
rrn4 = np.random.random({2,3,3})
rrn4

TypeError: expected a sequence of integers or a single integer, got '{2, 3}'

In [80]:
np.random.seed(100)
tup1 = (2,3,4)
rrn5 = np.random.random(tup1)
rrn5

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613],
        [0.00471886, 0.12156912, 0.67074908, 0.82585276],
        [0.13670659, 0.57509333, 0.89132195, 0.20920212]],

       [[0.18532822, 0.10837689, 0.21969749, 0.97862378],
        [0.81168315, 0.17194101, 0.81622475, 0.27407375],
        [0.43170418, 0.94002982, 0.81764938, 0.33611195]]])

## 8)Creating using `np.random.rand()`

In [81]:
np.random.seed(100)
rrd1 = np.random.rand(8)
rrd1

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276])

In [82]:
np.random.seed(110)
rrd2 = np.random.rand(4,5)
rrd2

array([[0.11605886, 0.65845538, 0.37558898, 0.61278258, 0.67949055],
       [0.68246313, 0.95501   , 0.63722294, 0.51294361, 0.08617633],
       [0.38746845, 0.29044365, 0.13540107, 0.01010558, 0.41283188],
       [0.4925909 , 0.02139758, 0.55951007, 0.07761669, 0.40766636]])

In [83]:
np.random.seed(100)
rrd3 = np.random.rand(3,2,5)
rrd3

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333]],

       [[0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497]]])

In [84]:
tup1 = (2,4,5)
rrd4 = np.random.rand(tup1)

TypeError: 'tuple' object cannot be interpreted as an integer

In [85]:
np.random.seed(100)
rrd5 = np.random.rand(*tup1)
rrd5

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])