In [1]:
import numpy as np

In [2]:
np.random.seed(1)
a = np.random.randint(2,10,size=(10,))
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [3]:
b = np.array([[11,2,3,44,5,6,77],[21,23,43,54,66,7,0],[1,44,82,36,77,9,100],[111,444,52,16,779,91,10]])
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [4]:
np.random.seed(100)
c = np.random.rand(2,4,5)
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

# Demonstrating important ndarray's Attributes

## 1)`.ndim` Attribute:-

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
c.ndim

3

## 2)`.shape` Attribute:-

In [8]:
a.shape

(10,)

In [9]:
b.shape

(4, 7)

In [10]:
c.shape

(2, 4, 5)

## 3)`.size` Attribute:-

In [11]:
a.size

10

In [12]:
b.size

28

In [13]:
c.size

40

## 4)`.itemsize` Attribute:-

In [14]:
a.itemsize

4

In [15]:
b.itemsize

4

In [16]:
c.itemsize

8

## 5)`.nbytes` Attribute:-

In [17]:
a.nbytes

40

In [18]:
b.nbytes

112

In [19]:
c.nbytes

320

## 6)`.dtype` Attribute:-

In [20]:
a.dtype

dtype('int32')

In [21]:
b.dtype

dtype('int32')

In [22]:
c.dtype

dtype('float64')

## 7)`.strides` Attribute:-

In [23]:
a.strides

(4,)

In [24]:
b.strides

(28, 4)

In [25]:
c.strides

(160, 40, 8)

## 8)`.flat` Attribute:-

In [26]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [27]:
fga = a.flat
print(next(fga))
print(next(fga))
next(fga)
print(next(fga))

7
5
2


In [28]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [29]:
fgb = b.flat
print(next(fgb))
print(next(fgb))
next(fgb)
next(fgb)
next(fgb)
next(fgb)
next(fgb)
next(fgb)
next(fgb)
next(fgb)
print(next(fgb))

11
2
54


In [30]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [31]:
fgc = c.flat
print(next(fgc))
print(next(fgc))
next(fgc)
next(fgc)
next(fgc)
next(fgc)
next(fgc)
next(fgc)
next(fgc)
next(fgc)
print(next(fgc))

0.5434049417909654
0.27836938509379616
0.891321954312264


# Demonstrating important ndarray Methods(Utility)

## 1)`.reshape()` Method:-

In [32]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [33]:
a1 = a.reshape(2,5)
a1

array([[7, 5, 6, 2, 9],
       [3, 5, 7, 9, 2]])

In [34]:
a2 = a.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [35]:
b,b.shape

(array([[ 11,   2,   3,  44,   5,   6,  77],
        [ 21,  23,  43,  54,  66,   7,   0],
        [  1,  44,  82,  36,  77,   9, 100],
        [111, 444,  52,  16, 779,  91,  10]]),
 (4, 7))

In [36]:
b1 = b.reshape(2,2,7)
b1

array([[[ 11,   2,   3,  44,   5,   6,  77],
        [ 21,  23,  43,  54,  66,   7,   0]],

       [[  1,  44,  82,  36,  77,   9, 100],
        [111, 444,  52,  16, 779,  91,  10]]])

In [37]:
b2 = b.reshape(2,14)
b2

array([[ 11,   2,   3,  44,   5,   6,  77,  21,  23,  43,  54,  66,   7,
          0],
       [  1,  44,  82,  36,  77,   9, 100, 111, 444,  52,  16, 779,  91,
         10]])

In [38]:
b3 = b.reshape(3,4,2)

ValueError: cannot reshape array of size 28 into shape (3,4,2)

## 2)`.transpose()` Method:-

In [39]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [40]:
at1 = a.transpose()
at1

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [41]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [42]:
bt1 = b.transpose()
bt1

array([[ 11,  21,   1, 111],
       [  2,  23,  44, 444],
       [  3,  43,  82,  52],
       [ 44,  54,  36,  16],
       [  5,  66,  77, 779],
       [  6,   7,   9,  91],
       [ 77,   0, 100,  10]])

In [43]:
bt2 = b.transpose((1,0))
bt2

array([[ 11,  21,   1, 111],
       [  2,  23,  44, 444],
       [  3,  43,  82,  52],
       [ 44,  54,  36,  16],
       [  5,  66,  77, 779],
       [  6,   7,   9,  91],
       [ 77,   0, 100,  10]])

In [44]:
bt3 = b.transpose((0,1))
bt3

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [45]:
bt4 = b.transpose(1,0)
bt4

array([[ 11,  21,   1, 111],
       [  2,  23,  44, 444],
       [  3,  43,  82,  52],
       [ 44,  54,  36,  16],
       [  5,  66,  77, 779],
       [  6,   7,   9,  91],
       [ 77,   0, 100,  10]])

In [46]:
bt5 = b.transpose(0,0)
bt5

ValueError: repeated axis in transpose

In [47]:
bt6 = b.transpose(0,1,2)
bt6

ValueError: axes don't match array

In [48]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [49]:
ct1 = c.transpose()
ct1

array([[[0.54340494, 0.43170418],
        [0.12156912, 0.37283205],
        [0.89132195, 0.59884338],
        [0.97862378, 0.89041156]],

       [[0.27836939, 0.94002982],
        [0.67074908, 0.00568851],
        [0.20920212, 0.60380454],
        [0.81168315, 0.98092086]],

       [[0.42451759, 0.81764938],
        [0.82585276, 0.25242635],
        [0.18532822, 0.10514769],
        [0.17194101, 0.05994199]],

       [[0.84477613, 0.33611195],
        [0.13670659, 0.79566251],
        [0.10837689, 0.38194344],
        [0.81622475, 0.89054594]],

       [[0.00471886, 0.17541045],
        [0.57509333, 0.01525497],
        [0.21969749, 0.03647606],
        [0.27407375, 0.5769015 ]]])

In [50]:
ct2 = c.transpose((1,0,2))
ct2

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045]],

       [[0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497]],

       [[0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606]],

       [[0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [51]:
ct3 = c.transpose(2,0,1)
ct3

array([[[0.54340494, 0.12156912, 0.89132195, 0.97862378],
        [0.43170418, 0.37283205, 0.59884338, 0.89041156]],

       [[0.27836939, 0.67074908, 0.20920212, 0.81168315],
        [0.94002982, 0.00568851, 0.60380454, 0.98092086]],

       [[0.42451759, 0.82585276, 0.18532822, 0.17194101],
        [0.81764938, 0.25242635, 0.10514769, 0.05994199]],

       [[0.84477613, 0.13670659, 0.10837689, 0.81622475],
        [0.33611195, 0.79566251, 0.38194344, 0.89054594]],

       [[0.00471886, 0.57509333, 0.21969749, 0.27407375],
        [0.17541045, 0.01525497, 0.03647606, 0.5769015 ]]])

## 3)`.ravel()` Method:-

In [52]:
rv1 = a.ravel()
rv1

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [53]:
rv2 = b.ravel()
rv2

array([ 11,   2,   3,  44,   5,   6,  77,  21,  23,  43,  54,  66,   7,
         0,   1,  44,  82,  36,  77,   9, 100, 111, 444,  52,  16, 779,
        91,  10])

In [54]:
rv3 = c.ravel()
rv3

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333,
       0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375,
       0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045,
       0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497,
       0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ])

## 4)`.max()` Method:-

In [55]:
mx1 = a.max()
mx1

9

In [56]:
mx2 = b.max()
mx2

779

In [57]:
mx3 = c.max()
mx3

0.9809208570123115

In [58]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [59]:
mx4 = b.max(axis=1)
mx4

array([ 77,  66, 100, 779])

In [60]:
mx5 = b.max(axis=0)
mx5

array([111, 444,  82,  54, 779,  91, 100])

In [61]:
mx6 = b.max(axis=(0,1))
mx6

779

In [62]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [63]:
mx7 = c.max(axis=0)
mx7

array([[0.54340494, 0.94002982, 0.81764938, 0.84477613, 0.17541045],
       [0.37283205, 0.67074908, 0.82585276, 0.79566251, 0.57509333],
       [0.89132195, 0.60380454, 0.18532822, 0.38194344, 0.21969749],
       [0.97862378, 0.98092086, 0.17194101, 0.89054594, 0.5769015 ]])

In [64]:
mx8 = c.max(axis=1)
mx8

array([[0.97862378, 0.81168315, 0.82585276, 0.84477613, 0.57509333],
       [0.89041156, 0.98092086, 0.81764938, 0.89054594, 0.5769015 ]])

In [65]:
mx9 = c.max(axis=2)
mx9

array([[0.84477613, 0.82585276, 0.89132195, 0.97862378],
       [0.94002982, 0.79566251, 0.60380454, 0.98092086]])

In [66]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [67]:
mx10 = c.max(axis=(0,1))
mx10

array([0.97862378, 0.98092086, 0.82585276, 0.89054594, 0.5769015 ])

In [68]:
mx10 = c.max(axis=(1,0))
mx10

array([0.97862378, 0.98092086, 0.82585276, 0.89054594, 0.5769015 ])

In [69]:
mx11 = c.max(axis=(0,2))
mx11

array([0.94002982, 0.82585276, 0.89132195, 0.98092086])

In [70]:
mx12 = c.max(axis=(1,2))
mx12

array([0.97862378, 0.98092086])

In [71]:
mx13 = c.max(axis=(2,1,0))
mx13

0.9809208570123115

## 5)`.min()` Method:-

In [72]:
mn1 = a.min()
mn1

2

In [73]:
mn2 = b.min()
mn2

0

In [74]:
mn3 = c.min()
mn3

0.004718856190972565

In [75]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [76]:
mn3 = b.min(axis=1)
mn3

array([ 2,  0,  1, 10])

In [77]:
mn4 = b.min(axis=0)
mn4

array([ 1,  2,  3, 16,  5,  6,  0])

In [78]:
mn5 = b.min(axis=(1,0))
mn5

0

In [79]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [80]:
mn6 = c.min(axis=0)
mn6

array([[0.43170418, 0.27836939, 0.42451759, 0.33611195, 0.00471886],
       [0.12156912, 0.00568851, 0.25242635, 0.13670659, 0.01525497],
       [0.59884338, 0.20920212, 0.10514769, 0.10837689, 0.03647606],
       [0.89041156, 0.81168315, 0.05994199, 0.81622475, 0.27407375]])

In [81]:
mn7 = c.min(axis=1)
mn7

array([[0.12156912, 0.20920212, 0.17194101, 0.10837689, 0.00471886],
       [0.37283205, 0.00568851, 0.05994199, 0.33611195, 0.01525497]])

In [82]:
mn8 = c.min(axis=2)
mn8

array([[0.00471886, 0.12156912, 0.10837689, 0.17194101],
       [0.17541045, 0.00568851, 0.03647606, 0.05994199]])

In [83]:
mn9 = c.min(axis=(0,1))
mn9

array([0.12156912, 0.00568851, 0.05994199, 0.10837689, 0.00471886])

In [84]:
mn10 = c.min(axis=(2,0))
mn10

array([0.00471886, 0.00568851, 0.03647606, 0.05994199])

In [85]:
mn11 = c.min(axis=(1,2))
mn11

array([0.00471886, 0.00568851])

In [86]:
mn12 = c.min(axis=(2,0,1))
mn12

0.004718856190972565

## 6)`.mean()` Method:-

In [87]:
me1 = a.mean()
me1

5.5

In [88]:
me2 = b.mean()
me2

79.07142857142857

In [89]:
me3 = c.mean()
me3

0.45899845090724956

In [90]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [91]:
me4 = b.mean(axis=1)
me4

array([ 21.14285714,  30.57142857,  49.85714286, 214.71428571])

In [92]:
me5 = b.mean(axis=0)
me5

array([ 36.  , 128.25,  45.  ,  37.5 , 231.75,  28.25,  46.75])

In [93]:
me6 = b.mean(axis=(1,0))
me6

79.07142857142857

In [94]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [95]:
me7 = c.mean(axis=0)
me7

array([[0.48755456, 0.6091996 , 0.62108348, 0.59044404, 0.09006465],
       [0.24720058, 0.3382188 , 0.53913955, 0.46618455, 0.29517415],
       [0.74508267, 0.40650333, 0.14523795, 0.24516017, 0.12808677],
       [0.93451767, 0.896302  , 0.1159415 , 0.85338535, 0.42548762]])

In [96]:
me8 = c.mean(axis=1)
me8

array([[0.63372995, 0.49250094, 0.40190989, 0.47652109, 0.26839586],
       [0.57344779, 0.63261093, 0.30879135, 0.60106596, 0.20101075]])

In [97]:
me9 = c.mean(axis=2)
me9

array([[0.41915738, 0.46599418, 0.32278534, 0.61050929],
       [0.54018116, 0.28837288, 0.34524302, 0.67974437]])

In [98]:
me10 = c.mean(axis=(1,0))
me10

array([0.60358887, 0.56255593, 0.35535062, 0.53879353, 0.2347033 ])

In [99]:
me11 = c.mean(axis=(0,2))
me11

array([0.47966927, 0.37718353, 0.33401418, 0.64512683])

In [100]:
me12 = c.mean(axis=(1,2))
me12

array([0.45461155, 0.46338536])

In [101]:
me13 = c.mean(axis=(0,1,2))
me13

0.45899845090724956

## 7)`.std()` Method:-

In [102]:
st1 = a.std()
st1

2.4596747752497685

In [103]:
st2 = b.std()
st2

157.74548410367265

In [104]:
st3 = c.std()
st3

0.3217139478081803

In [105]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [106]:
st4 = b.std(axis=0)
st4

array([ 43.87482194, 182.90212547,  28.22233158,  13.95528574,
       317.14300796,  36.24482722,  42.68123124])

In [107]:
st5 = b.std(axis=1)
st5

array([ 26.54068882,  22.67066791,  34.98337798, 268.57386017])

In [108]:
st6 = b.std(axis=(1,0))
st6

157.74548410367265

In [109]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [110]:
st7 = c.std(axis=0)
st7

array([[0.05585038, 0.33083022, 0.19656589, 0.25433209, 0.0853458 ],
       [0.12563146, 0.33253029, 0.2867132 , 0.32947796, 0.27991918],
       [0.14623929, 0.19730121, 0.04009027, 0.13678328, 0.09161072],
       [0.04410611, 0.08461885, 0.05599951, 0.0371606 , 0.15141388]])

In [111]:
st8 = c.std(axis=1)
st8

array([[0.33755471, 0.25483339, 0.26459023, 0.35426487, 0.20371099],
       [0.20090352, 0.39041251, 0.30228722, 0.24488864, 0.22556934]])

In [112]:
st9 = c.std(axis=2)
st9

array([[0.27863886, 0.2864906 , 0.28692423, 0.32367547],
       [0.29097654, 0.28992141, 0.23895478, 0.3388973 ]])

In [113]:
st10 = c.std(axis=(0,1))
st10

array([0.27939432, 0.33702922, 0.28785507, 0.31082934, 0.21754318])

In [114]:
st11 = c.std(axis=(2,0))
st11

array([0.29123044, 0.30158411, 0.26426982, 0.33317708])

In [115]:
st12  = c.std(axis=(1,2))
st12

array([0.31220051, 0.33089588])

In [116]:
st13 = c.std(axis=(0,1,2))
st13

0.3217139478081803

## 8)`.argmax()` Method:-

In [117]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [118]:
agmx1 = a.argmax()
agmx1

4

In [119]:
agmx3 = b.argmax()
agmx3

25

In [120]:
agmx4 = c.argmax()
agmx4

36

In [121]:
a1 = np.array([1,2,3,4,7,92,3,4,7])
agmx2 = a1.argmax()
agmx2

5

In [122]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [123]:
agmx5 = b.argmax(axis=0)
agmx5

array([3, 3, 2, 1, 3, 3, 2], dtype=int64)

In [124]:
agmx6 = b.argmax(axis=1)
agmx6

array([6, 4, 6, 4], dtype=int64)

In [125]:
b1 =np.array([[9,8,9,9],[8,1,2,5],[7,7,8,6],[9,9,9,9]])
b1.argmax(axis=0)

array([0, 3, 0, 0], dtype=int64)

In [126]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [127]:
agmx7 = c.argmax(axis=0)
agmx7

array([[0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 1]], dtype=int64)

In [128]:
agmx8 = c.argmax(axis=1)
agmx8

array([[3, 3, 1, 0, 1],
       [3, 3, 0, 3, 3]], dtype=int64)

In [129]:
agmx9 = c.argmax(axis=2)
agmx9

array([[3, 2, 0, 0],
       [1, 3, 1, 1]], dtype=int64)

In [130]:
agmx10 = c.argmax(axis=(1,0))
agmx10

TypeError: 'tuple' object cannot be interpreted as an integer

## 9)`.argmin()` Method:-

In [131]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [132]:
agmn1 = a.argmin()
agmn1

3

In [133]:
agmn2 = b.argmin()
agmn2

13

In [134]:
agmn3 = c.argmin()
agmn3

4

In [135]:
a1 = np.array([1,2,3,4,7,92,3,4,1])
agmn2 = a1.argmin()
agmn2

0

In [136]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [137]:
agmn4 = b.argmin(axis=0)
agmn4

array([2, 0, 0, 3, 0, 0, 1], dtype=int64)

In [138]:
agmn5 = b.argmin(axis=1)
agmn5

array([1, 6, 0, 6], dtype=int64)

In [139]:
b1 =np.array([[7,8,7,7],[88,11,22,15],[9,9,8,16],[7,7,7,7]])
b1.argmax(axis=0)

array([1, 1, 1, 2], dtype=int64)

In [140]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [141]:
agmn6 = c.argmin(axis=0)
agmn6

array([[1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0]], dtype=int64)

In [142]:
agmn7 = c.argmin(axis=1)
agmn7

array([[1, 2, 3, 2, 0],
       [1, 1, 3, 0, 1]], dtype=int64)

In [143]:
agmn8 = c.argmin(axis=2)
agmn8

array([[4, 0, 3, 2],
       [4, 1, 4, 2]], dtype=int64)

In [144]:
agmn9 = c.argmin(axis=(1,0))
agmn9

TypeError: 'tuple' object cannot be interpreted as an integer

## 10)`.sum()` Method:-

In [145]:
sm1 = a.sum()
sm1

55

In [146]:
sm2 = b.sum()
sm2

2214

In [147]:
sm3 = c.sum()
sm3

18.359938036289982

In [148]:
sm4 = a.sum(initial=5)
sm4

60

In [149]:
ws1 = b % 11 == 0
sm5 = b.sum(where=ws1)
sm5

319

In [150]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [151]:
sm6 = b.sum(axis=0)
sm6

array([144, 513, 180, 150, 927, 113, 187])

In [152]:
sm7 = b.sum(axis=1)
sm7

array([ 148,  214,  349, 1503])

In [153]:
sm8 = b.sum(axis=(0,1))
sm8

2214

In [154]:
sm9 = b.sum(axis=0,where=ws1)
sm9

array([ 11,  44,   0,  44, 143,   0,  77])

In [155]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [156]:
sm10 = c.sum(axis=0)
sm10

array([[0.97510913, 1.2183992 , 1.24216697, 1.18088808, 0.18012931],
       [0.49440117, 0.67643759, 1.07827911, 0.9323691 , 0.5903483 ],
       [1.49016533, 0.81300666, 0.2904759 , 0.49032034, 0.25617355],
       [1.86903535, 1.79260401, 0.231883  , 1.70677069, 0.85097525]])

In [157]:
sm11 = c.sum(axis=1)
sm11

array([[2.5349198 , 1.97000374, 1.60763958, 1.90608436, 1.07358343],
       [2.29379117, 2.53044372, 1.23516541, 2.40426385, 0.80404298]])

In [158]:
sm12 = c.sum(axis=2)
sm12

array([[2.09578691, 2.32997088, 1.61392668, 3.05254644],
       [2.70090579, 1.44186439, 1.7262151 , 3.39872185]])

In [159]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [160]:
sm13 = c.sum(axis=(0,1))
sm13

array([4.82871097, 4.50044746, 2.84280498, 4.31034821, 1.87762641])

In [161]:
sm14 = c.sum(axis=(0,2))
sm14

array([4.79669269, 3.77183527, 3.34014178, 6.4512683 ])

In [162]:
sm15 = c.sum(axis=(1,2))
sm15

array([9.09223091, 9.26770713])

In [163]:
sm16 = c.sum(axis=(0,1,2))
sm16

18.359938036289982

## 11)`.prod()` Method:-

In [164]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [165]:
pd1 = a.prod()
pd1

7144200

In [166]:
pd2 = b.prod()
pd2

0

In [167]:
pd3 = c.prod()
pd3

6.170879202991875e-23

In [168]:
pd4 = a.prod(initial=2)
pd4 

14288400

In [169]:
wp1 = b % 11 !=0 
pd5 = b.prod(where=wp1)
pd5

1902247936

In [170]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [171]:
pd6 = b.prod(axis=0)
pd6

array([   25641,   898656,   550056,  1368576, 19794390,    34398,
              0])

In [172]:
pd7 = b.prod(axis=1)
pd7

array([   6708240,          0,  411303808, -808939008])

In [173]:
pd8 = b.prod(axis=(0,1))
pd8

0

In [174]:
pd9 = b.prod(axis=1,where=wp1)
pd9

array([       180,    7850682,    2656800, -808939008])

In [175]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [176]:
pd10 = c.prod(axis=0)
pd10

array([[2.34590187e-01, 2.61675523e-01, 3.47106544e-01, 2.83939353e-01,
        8.27736706e-04],
       [4.53248641e-02, 3.81556110e-03, 2.08466999e-01, 1.08772308e-01,
        8.77303220e-03],
       [5.33762249e-01, 1.26317191e-01, 1.94868333e-02, 4.13938429e-02,
        8.01369817e-03],
       [8.71377934e-01, 7.96196930e-01, 1.03064863e-02, 7.26885640e-01,
        1.58113556e-01]])

In [177]:
pd11 = c.prod(axis=1)
pd11

array([[5.76231811e-02, 3.17054685e-02, 1.11717021e-02, 1.02159211e-02,
        1.63405854e-04],
       [8.58229689e-02, 3.16716214e-03, 1.30086632e-03, 9.09637256e-02,
        5.63088184e-05]])

In [178]:
pd12 = c.prod(axis=2)
pd12

array([[2.55987714e-04, 5.29436363e-03, 8.22818466e-04, 3.05533597e-02],
       [1.95629536e-02, 6.49810223e-06, 5.29683303e-04, 2.68976233e-02]])

In [179]:
pd13 = c.prod(axis=(0,1))
pd13

array([4.94539248e-03, 1.00416359e-04, 1.45328910e-05, 9.29278243e-04,
       9.20119054e-09])

In [180]:
pd14 = c.prod(axis=(0,2))
pd14

array([5.00787577e-06, 3.44033161e-08, 4.35833203e-07, 8.21812760e-04])

In [181]:
pd15 = c.prod(axis=(1,2))
pd15

array([3.40718638e-11, 1.81113638e-12])

In [182]:
pd16 = c.prod(axis=(0,1,2))
pd16

6.170879202991875e-23

## 12)`.cumsum()` Method:-

In [183]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [184]:
csm1 = a.cumsum()
csm1

array([ 7, 12, 18, 20, 29, 32, 37, 44, 53, 55])

In [185]:
csm2 = b.cumsum()
csm2

array([  11,   13,   16,   60,   65,   71,  148,  169,  192,  235,  289,
        355,  362,  362,  363,  407,  489,  525,  602,  611,  711,  822,
       1266, 1318, 1334, 2113, 2204, 2214])

In [186]:
csm3 = c.cumsum()
csm3

array([ 0.54340494,  0.82177433,  1.24629192,  2.09106805,  2.09578691,
        2.21735603,  2.88810511,  3.71395787,  3.85066446,  4.42575779,
        5.31707974,  5.52628186,  5.71161008,  5.81998697,  6.03968446,
        7.01830825,  7.8299914 ,  8.00193241,  8.81815716,  9.09223091,
        9.52393509, 10.46396491, 11.28161429, 11.61772624, 11.79313669,
       12.16596874, 12.17165725, 12.4240836 , 13.21974611, 13.23500108,
       13.83384446, 14.437649  , 14.54279668, 14.92474013, 14.96121618,
       15.85162775, 16.8325486 , 16.89249059, 17.78303654, 18.35993804])

In [187]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [188]:
csm4 = b.cumsum(axis=0)
csm4

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 32,  25,  46,  98,  71,  13,  77],
       [ 33,  69, 128, 134, 148,  22, 177],
       [144, 513, 180, 150, 927, 113, 187]])

In [189]:
csm5 = b.cumsum(axis=1)
csm5

array([[  11,   13,   16,   60,   65,   71,  148],
       [  21,   44,   87,  141,  207,  214,  214],
       [   1,   45,  127,  163,  240,  249,  349],
       [ 111,  555,  607,  623, 1402, 1493, 1503]])

In [190]:
csm6 = b.cumsum(axis=(0,1))
csm6

TypeError: 'tuple' object cannot be interpreted as an integer

In [191]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [192]:
csm7 = c.cumsum(axis=0)
csm7

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.97510913, 1.2183992 , 1.24216697, 1.18088808, 0.18012931],
        [0.49440117, 0.67643759, 1.07827911, 0.9323691 , 0.5903483 ],
        [1.49016533, 0.81300666, 0.2904759 , 0.49032034, 0.25617355],
        [1.86903535, 1.79260401, 0.231883  , 1.70677069, 0.85097525]]])

In [193]:
csm8 = c.cumsum(axis=1)
csm8

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.66497406, 0.94911847, 1.25037035, 0.98148272, 0.57981219],
        [1.55629602, 1.15832059, 1.43569857, 1.08985961, 0.79950968],
        [2.5349198 , 1.97000374, 1.60763958, 1.90608436, 1.07358343]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.80453623, 0.94571833, 1.07007573, 1.13177446, 0.19066542],
        [1.40337961, 1.54952287, 1.17522342, 1.5137179 , 0.22714148],
        [2.29379117, 2.53044372, 1.23516541, 2.40426385, 0.80404298]]])

In [194]:
csm9 = c.cumsum(axis=2)
csm9

array([[[0.54340494, 0.82177433, 1.24629192, 2.09106805, 2.09578691],
        [0.12156912, 0.79231821, 1.61817096, 1.75487755, 2.32997088],
        [0.89132195, 1.10052408, 1.2858523 , 1.39422919, 1.61392668],
        [0.97862378, 1.79030693, 1.96224795, 2.7784727 , 3.05254644]],

       [[0.43170418, 1.371734  , 2.18938338, 2.52549533, 2.70090579],
        [0.37283205, 0.37852055, 0.63094691, 1.42660942, 1.44186439],
        [0.59884338, 1.20264792, 1.3077956 , 1.68973905, 1.7262151 ],
        [0.89041156, 1.87133242, 1.93127441, 2.82182035, 3.39872185]]])

In [195]:
csm10 = c.cumsum(axis=(0,1))
csm10

TypeError: 'tuple' object cannot be interpreted as an integer

## 13)`.cumprod()` Method:-

In [196]:
a

array([7, 5, 6, 2, 9, 3, 5, 7, 9, 2])

In [197]:
cpd1 = a.cumprod()
cpd1

array([      7,      35,     210,     420,    3780,   11340,   56700,
        396900, 3572100, 7144200])

In [198]:
cpd2 = b.cumprod()
cpd2

array([         11,          22,          66,        2904,       14520,
             87120,     6708240,   140873040, -1054887376,  1884483088,
       -1317128352, -1031125312,  1372057408,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0,           0,           0,
                 0,           0,           0])

In [199]:
cpd3 = c.cumprod()
cpd3

array([5.43404942e-01, 1.51267300e-01, 6.42156295e-02, 5.42478312e-02,
       2.55987714e-04, 3.11202013e-05, 2.08738465e-05, 1.72387237e-05,
       2.35664712e-06, 1.35529204e-06, 1.20800155e-06, 2.52716488e-07,
       4.68354968e-08, 5.07588550e-09, 1.11515932e-09, 1.09132143e-09,
       8.85807217e-10, 1.52306590e-10, 1.24316408e-10, 3.40718638e-11,
       1.47089661e-11, 1.38268668e-11, 1.13055290e-11, 3.79992341e-12,
       6.66546290e-13, 2.48509817e-13, 1.41364992e-15, 3.56842495e-16,
       2.83926195e-16, 4.33128594e-18, 2.59376190e-18, 1.56612521e-18,
       1.64674441e-19, 6.28963231e-20, 2.29420984e-21, 2.04279097e-21,
       2.00381627e-21, 1.20112732e-22, 1.06965907e-22, 6.17087920e-23])

In [200]:
b

array([[ 11,   2,   3,  44,   5,   6,  77],
       [ 21,  23,  43,  54,  66,   7,   0],
       [  1,  44,  82,  36,  77,   9, 100],
       [111, 444,  52,  16, 779,  91,  10]])

In [201]:
cpd4 = b.cumprod(axis=0)
cpd4

array([[      11,        2,        3,       44,        5,        6,
              77],
       [     231,       46,      129,     2376,      330,       42,
               0],
       [     231,     2024,    10578,    85536,    25410,      378,
               0],
       [   25641,   898656,   550056,  1368576, 19794390,    34398,
               0]])

In [202]:
cpd5 = b.cumprod(axis=1)
cpd5

array([[        11,         22,         66,       2904,      14520,
             87120,    6708240],
       [        21,        483,      20769,    1121526,   74020716,
         518145012,          0],
       [         1,         44,       3608,     129888,   10001376,
          90012384,  411303808],
       [       111,      49284,    2562768,   41004288, 1877569280,
        -939887360, -808939008]])

In [203]:
cpd6 = b.cumprod(axis=(0,1))
cpd6

TypeError: 'tuple' object cannot be interpreted as an integer

In [204]:
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [205]:
cpd7 = c.cumprod(axis=0)
cpd7

array([[[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, 8.44776132e-01,
         4.71885619e-03],
        [1.21569121e-01, 6.70749085e-01, 8.25852755e-01, 1.36706590e-01,
         5.75093329e-01],
        [8.91321954e-01, 2.09202122e-01, 1.85328220e-01, 1.08376890e-01,
         2.19697493e-01],
        [9.78623785e-01, 8.11683149e-01, 1.71941013e-01, 8.16224749e-01,
         2.74073747e-01]],

       [[2.34590187e-01, 2.61675523e-01, 3.47106544e-01, 2.83939353e-01,
         8.27736706e-04],
        [4.53248641e-02, 3.81556110e-03, 2.08466999e-01, 1.08772308e-01,
         8.77303220e-03],
        [5.33762249e-01, 1.26317191e-01, 1.94868333e-02, 4.13938429e-02,
         8.01369817e-03],
        [8.71377934e-01, 7.96196930e-01, 1.03064863e-02, 7.26885640e-01,
         1.58113556e-01]]])

In [206]:
cpd8 = c.cumprod(axis=1)
cpd8

array([[[5.43404942e-01, 2.78369385e-01, 4.24517591e-01, 8.44776132e-01,
         4.71885619e-03],
        [6.60612610e-02, 1.86716010e-01, 3.50589022e-01, 1.15486464e-01,
         2.71378272e-03],
        [5.88818523e-02, 3.90613856e-02, 6.49740392e-02, 1.25160639e-02,
         5.96211259e-04],
        [5.76231811e-02, 3.17054685e-02, 1.11717021e-02, 1.02159211e-02,
         1.63405854e-04]],

       [[4.31704184e-01, 9.40029820e-01, 8.17649379e-01, 3.36111950e-01,
         1.75410454e-01],
        [1.60953154e-01, 5.34736654e-03, 2.06396251e-01, 2.67431677e-01,
         2.67588143e-03],
        [9.63857304e-02, 3.22876419e-03, 2.17020881e-02, 1.02143776e-01,
         9.76056024e-05],
        [8.58229689e-02, 3.16716214e-03, 1.30086632e-03, 9.09637256e-02,
         5.63088184e-05]]])

In [207]:
cpd9 = c.cumprod(axis=2)
cpd9

array([[[5.43404942e-01, 1.51267300e-01, 6.42156295e-02, 5.42478312e-02,
         2.55987714e-04],
        [1.21569121e-01, 8.15423765e-02, 6.73419963e-02, 9.20609466e-03,
         5.29436363e-03],
        [8.91321954e-01, 1.86466444e-01, 3.45574941e-02, 3.74523376e-03,
         8.22818466e-04],
        [9.78623785e-01, 7.94332435e-01, 1.36578323e-01, 1.11478608e-01,
         3.05533597e-02]],

       [[4.31704184e-01, 4.05814806e-01, 3.31814224e-01, 1.11526726e-01,
         1.95629536e-02],
        [3.72832046e-01, 2.12085784e-03, 5.35360410e-04, 4.25966207e-04,
         6.49810223e-06],
        [5.98843377e-01, 3.61584349e-01, 3.80197574e-02, 1.45213971e-02,
         5.29683303e-04],
        [8.90411563e-01, 8.73423274e-01, 5.23547281e-02, 4.66242908e-02,
         2.68976233e-02]]])

In [208]:
cpd10 = c.cumprod(axis=(0,1))
cpd10

TypeError: 'tuple' object cannot be interpreted as an integer

## 14)`.astype()` Method:-

In [ ]:
a,a.dtype

In [ ]:
a1 = a.astype(np.float32)
a1

In [ ]:
b

In [ ]:
b1 = b.astype(str)
b1

In [ ]:
a[0]

In [ ]:
a

In [ ]:
a[-1]

In [ ]:
a[[1,2,3]]

In [ ]:
a[(1,3,5)]

In [ ]:
a[[1,3,-3,-1]]

In [ ]:
a[[True,False,True,False,True,False,True,False,True]]

In [ ]:
b

In [ ]:
b[1,5]

In [ ]:
b[2,6]

In [ ]:
b[2]

In [ ]:
b[1]

In [ ]:
b[-1,-1]

In [ ]:
b[-1]

In [ ]:
b[[[2,3],[1,1]]]

In [ ]:
lst1 = [1,-1,-5,2]
a[lst1]

In [ ]:
b[2,3]

In [ ]:
b[[1,2],[1,2]]

In [ ]:
b[[1,2]]

In [ ]:
c

In [ ]:
c[0,1,3]

In [ ]:
c[0]

In [ ]:
c[0,1]

In [ ]:
c[0,1][2]

In [ ]:
c[0][1,4]

In [ ]:
c[[0,1,1],[2,3,1],[2,3,2]]

In [ ]:
a

In [ ]:
a[0:4]

In [ ]:
a[-6:-1]

In [ ]:
b

In [ ]:
b[0:2,3:7]

In [ ]:
b[:,-7:-2]

In [ ]:
b[0:2,0:7:2]

In [ ]:
b[:,[1,5,6]]

In [ ]:
b[:,[0,1,2]]

In [ ]:
c

In [ ]:
c[0:1,1:3,2:4]

In [ ]:
c[0:2,:,1:3]

In [ ]:
c[0,:,[1,3,4]]

In [ ]:
bt1

In [ ]:
bt1[2,2]

In [ ]:
type(bt1)

In [ ]:
id(b)

In [ ]:
id(bt1)

In [ ]:
b

In [ ]:
b.argmax()

In [ ]:
b.argmax(keepdims=True)

In [ ]:
a1 = np.array([1,2,3,4,5,1,7,8,9,1])
a1.argmin()

In [ ]:
b1 = np.array([[9,9,9,9],[8,8,8,8],[7,7,7,7],[9,9,9,9]])
b1

In [ ]:
b1.argmax(axis=0)