In [1]:
import pandas as pd
import torch as th
import torchvision as thv
import numpy as np
import matplotlib.pyplot as plt
from torchinfo import summary
from sklearn.preprocessing import OneHotEncoder
import os
import time
SAVE_PATH = r"E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\OutputData\PyTorch\New folder"

## -->Setting the DEVICE Agnostic Code 

In [2]:
DEVICE = "cuda" if th.cuda.is_available() else "cpu"
DEVICE

'cuda'

### We can see in the Above Cell that we got `cuda` , Which means GPU is available and can be used for Training the Models

# --------------------------------------------------------------------------------------------

# -->Importing the Pre-BuiltIn Dataset(CIFAR-10)

### To Download and Use a Computer Vision Pre-BuiltIn Dataset we will use `torchvision.datasets.<DatasetName>` Method.

## -->For `torchvision.datasets.<DatatsetName>` Method:-This methods creates a TorchVision Dataset that will be a subclass of `torch.utils.data.Dataset` Class.

### < First Argument >(root):-It takes the Path(String) of the Location where we want to Download the Dataset.
### < Second Argument >(train):-If `True` it will Download the Training Dataset.If `False` it will Download the Test Dataset.
### < Third Argument >(download):-If `True` it will Download the Dataset from the Internet and Place it in the Specified Root Location,If the dataset is already Downloaded in the Location then it will not Download Again.
### < Fourth Argument >(transform):-It takes the Transforms/Function that will be applied on the X(Images) part of the Dataset.Its the part which helps in Performing Augmentation,Resizing etc and Converting the Image Data into `PyTorch Tensors`.
### < Fifth Argument >(target_transform):-It takes the Transforms/Function that will be applied on the Y(Labels) part of the Dataset.



#### `torchvison.dataset`:- [LINK](https://pytorch.org/vision/stable/datasets.html)

In [4]:
train_dataset = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                      train=True,
                                      download=True,
                                      transform=thv.transforms.Compose([thv.transforms.ToTensor()]))

test_dataset = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                    train=False,
                                    download=True,
                                    transform=thv.transforms.Compose([thv.transforms.ToTensor()]))

Files already downloaded and verified
Files already downloaded and verified


### In the Above Cell we have Downloaded the Train Dataset and Test Dataset of CIFAR-10 and also transformed the Images into PyTorch Tensor using `torchvision.transforms.ToTensor()` Method.

In [4]:
train_dataset_fg = thv.datasets.FashionMNIST(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                             train=True,
                                             download=True,
                                             transform=thv.transforms.Compose([thv.transforms.ToTensor()]))

test_dataset_fg = thv.datasets.FashionMNIST(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                           train=True,
                                           download=True,
                                           transform=thv.transforms.Compose([thv.transforms.ToTensor()]))

In [5]:
train_dataset_fg1 = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                      train=True,
                                      download=True,
                                      transform=thv.transforms.Compose([thv.transforms.ToTensor()]),
                                      target_transform=thv.transforms.Lambda(lambda y:y*100))

Files already downloaded and verified


### In the Above Cell we have Downloaded the Train Dataset and Test Dataset of FashionMNIST and also transformed the Images into PyTorch Tensors using `torchvision.transforms.ToTensor()` Method.

### -->We can Iterate and Index Over the Dataset Instance can also find the Length of the DataSet using `len()`

In [6]:
len(train_dataset)

50000

In [7]:
len(train_dataset_fg)

60000

In [8]:
len(test_dataset_fg)

60000

In [9]:
train_dataset[0]

(tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],
 
         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],
 
         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ...,

In [10]:
train_dataset_fg[10]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0431,
           0.5569, 0.7843, 0.4157, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.3333, 0.7255, 0.4392, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5961, 0.8392,
           0.8510, 0.7608, 0.9255, 0.8471, 0.7333, 0.5843, 0.5294, 0.6000,
           0.8275, 0.8510, 0.9059, 0.8039, 0.8510, 0.7373, 0.1333, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2588, 0.7255, 0.6510,
           0.7059, 0.7098, 0.7451, 0.8275, 0.8667, 0.7725, 0.5725, 0.7765,
           0.8078, 0.7490, 0.6588, 0.7451, 0.6745, 0.7373, 0.6863, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5294, 0.6000, 0.6275,
           0.6863, 0.7059, 0.6667, 0.7294, 0.7333, 0.7451, 0.7373, 0.7451,
           0.7333, 0.6824, 0.7647, 0.7255, 

In [11]:
train_dataset_fg1[100] 

(tensor([[[0.8353, 0.8275, 0.8275,  ..., 0.5922, 0.5922, 0.5843],
          [0.8392, 0.8314, 0.8314,  ..., 0.5961, 0.5961, 0.5922],
          [0.8471, 0.8392, 0.8353,  ..., 0.6000, 0.6000, 0.5922],
          ...,
          [0.5686, 0.5333, 0.5608,  ..., 0.8471, 0.7686, 0.7176],
          [0.5451, 0.5059, 0.5059,  ..., 0.8902, 0.8745, 0.8196],
          [0.5373, 0.5608, 0.5333,  ..., 0.8196, 0.8510, 0.8941]],
 
         [[0.8980, 0.8902, 0.8902,  ..., 0.6824, 0.6824, 0.6745],
          [0.8980, 0.8902, 0.8902,  ..., 0.6863, 0.6863, 0.6824],
          [0.8980, 0.8902, 0.8902,  ..., 0.6902, 0.6902, 0.6824],
          ...,
          [0.6235, 0.5804, 0.5961,  ..., 0.8510, 0.7725, 0.7176],
          [0.6000, 0.5569, 0.5451,  ..., 0.8941, 0.8784, 0.8196],
          [0.5961, 0.6078, 0.5686,  ..., 0.8196, 0.8510, 0.8941]],
 
         [[0.9490, 0.9412, 0.9412,  ..., 0.8078, 0.8078, 0.8000],
          [0.9451, 0.9373, 0.9373,  ..., 0.8118, 0.8118, 0.8039],
          [0.9373, 0.9294, 0.9294,  ...,

### In the Above Outputs we  an see the Transformed Data our Dataset Instance Hold.

## Accesing Some Important Attributes of `torchvision.datasets`:-

### 1)`.class_to_idx`:-Gives a Dictionary that Maps the Untransformed Labels to the Real Class names. 

In [12]:
train_dataset.class_to_idx

{'airplane': 0,
 'automobile': 1,
 'bird': 2,
 'cat': 3,
 'deer': 4,
 'dog': 5,
 'frog': 6,
 'horse': 7,
 'ship': 8,
 'truck': 9}

In [13]:
train_dataset_fg.class_to_idx

{'T-shirt/top': 0,
 'Trouser': 1,
 'Pullover': 2,
 'Dress': 3,
 'Coat': 4,
 'Sandal': 5,
 'Shirt': 6,
 'Sneaker': 7,
 'Bag': 8,
 'Ankle boot': 9}

In [14]:
train_dataset_fg1.class_to_idx

{'airplane': 0,
 'automobile': 1,
 'bird': 2,
 'cat': 3,
 'deer': 4,
 'dog': 5,
 'frog': 6,
 'horse': 7,
 'ship': 8,
 'truck': 9}

### 2)`.classes`:-Gives a list containing Real Names of all the Class Labels in the Same Order as the Above Dictionary.

In [15]:
train_dataset.classes

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [16]:
train_dataset_fg.classes

['T-shirt/top',
 'Trouser',
 'Pullover',
 'Dress',
 'Coat',
 'Sandal',
 'Shirt',
 'Sneaker',
 'Bag',
 'Ankle boot']

In [17]:
train_dataset_fg1.classes

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

### 3)`.root`:-Gives a String containig Location of the Root Directory where the Dataset was Downloaded.

In [18]:
train_dataset.root

'E:\\PyImage_ComputerVision\\DeepLearningFrameWorks\\Working Data\\InputData\\Pre-BuiltIn Datasets'

In [19]:
train_dataset_fg.root

'E:\\PyImage_ComputerVision\\DeepLearningFrameWorks\\Working Data\\InputData\\Pre-BuiltIn Datasets'

In [20]:
train_dataset_fg1.root

'E:\\PyImage_ComputerVision\\DeepLearningFrameWorks\\Working Data\\InputData\\Pre-BuiltIn Datasets'

### 4)`.transform`:-Gives the Transforms that were applied on the X(Images) part of the Dataset.

In [21]:
train_dataset.transform

Compose(
    ToTensor()
)

In [22]:
train_dataset_fg.transform

Compose(
    ToTensor()
)

In [23]:
train_dataset_fg1.transform

Compose(
    ToTensor()
)

### 5)`.target_transform`:-Gives the Transforms that were applied on the Y(Labels) part of the Dataset.

In [24]:
train_dataset.target_transform # As No Traget Transform was applied hence Nothing was Returned.

In [25]:
train_dataset_fg.target_transform # As No Traget Transform was applied hence Nothing was Returned.

In [26]:
train_dataset_fg1.target_transform

Lambda()

### 6)`.data`:-Gives a Instance Containing Collection of all the Original and UnTransformed X(Images) part of the Dataset

In [27]:
train_dataset.data

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [28]:
train_dataset_fg.data

tensor([[[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        ...,

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0,

In [29]:
train_dataset_fg1.data

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

### 7)`.targets`:-Gives an Instance Containing Collection of all the Original and UnTransformed Y(Labels) part of the Dataset.

In [30]:
train_dataset.targets

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


In [31]:
train_dataset_fg.targets

tensor([9, 0, 0,  ..., 3, 0, 5])

In [32]:
train_dataset_fg1.targets

[6,
 9,
 9,
 4,
 1,
 1,
 2,
 7,
 8,
 3,
 4,
 7,
 7,
 2,
 9,
 9,
 9,
 3,
 2,
 6,
 4,
 3,
 6,
 6,
 2,
 6,
 3,
 5,
 4,
 0,
 0,
 9,
 1,
 3,
 4,
 0,
 3,
 7,
 3,
 3,
 5,
 2,
 2,
 7,
 1,
 1,
 1,
 2,
 2,
 0,
 9,
 5,
 7,
 9,
 2,
 2,
 5,
 2,
 4,
 3,
 1,
 1,
 8,
 2,
 1,
 1,
 4,
 9,
 7,
 8,
 5,
 9,
 6,
 7,
 3,
 1,
 9,
 0,
 3,
 1,
 3,
 5,
 4,
 5,
 7,
 7,
 4,
 7,
 9,
 4,
 2,
 3,
 8,
 0,
 1,
 6,
 1,
 1,
 4,
 1,
 8,
 3,
 9,
 6,
 6,
 1,
 8,
 5,
 2,
 9,
 9,
 8,
 1,
 7,
 7,
 0,
 0,
 6,
 9,
 1,
 2,
 2,
 9,
 2,
 6,
 6,
 1,
 9,
 5,
 0,
 4,
 7,
 6,
 7,
 1,
 8,
 1,
 1,
 2,
 8,
 1,
 3,
 3,
 6,
 2,
 4,
 9,
 9,
 5,
 4,
 3,
 6,
 7,
 4,
 6,
 8,
 5,
 5,
 4,
 3,
 1,
 8,
 4,
 7,
 6,
 0,
 9,
 5,
 1,
 3,
 8,
 2,
 7,
 5,
 3,
 4,
 1,
 5,
 7,
 0,
 4,
 7,
 5,
 5,
 1,
 0,
 9,
 6,
 9,
 0,
 8,
 7,
 8,
 8,
 2,
 5,
 2,
 3,
 5,
 0,
 6,
 1,
 9,
 3,
 6,
 9,
 1,
 3,
 9,
 6,
 6,
 7,
 1,
 0,
 9,
 5,
 8,
 5,
 2,
 9,
 0,
 8,
 8,
 0,
 6,
 9,
 1,
 1,
 6,
 3,
 7,
 6,
 6,
 0,
 6,
 6,
 1,
 7,
 1,
 5,
 8,
 3,
 6,
 6,
 8,
 6,
 8,
 4,
 6,
 6,


# --------------------------------------------------------------------------------------------

## -->Now as One Hot Encoding the Labels in a Multi-Class CLassification Problem is always Beneficial and Better than Using Integer-Coded Labels

### Turning the CIFAR-10 Dataset Labels into One-Hot Encoded Vectors in the Below Cells Using `sklearn.preprocessing.OneHotEncoder` Class.

In [5]:
## Training the One Hot Encoder on the Previous Downloaded Targets

OHE = OneHotEncoder(sparse_output=False) 

OHE.fit(np.array(train_dataset.targets).reshape(-1,1))

OneHotEncoder(sparse_output=False)

In [36]:
OHE_train_dataset = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                         train=True,
                                         download=True,
                                         transform=thv.transforms.Compose([thv.transforms.ToTensor()]),
                                         target_transform=thv.transforms.Lambda(lambda x:th.tensor(OHE.transform([[x]]).squeeze(),dtype=th.float32)))

OHE_test_dataset = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                        train=False,
                                        download=True,
                                        transform=thv.transforms.Compose([thv.transforms.ToTensor()]),
                                        target_transform=thv.transforms.Lambda(lambda x:th.tensor(OHE.transform([[x]]).squeeze(),dtype=th.float32)))

Files already downloaded and verified
Files already downloaded and verified


### We can see in the Above Cell we have used One Hot Encoder Instance in the Target Transform to Obtain One Hot Encoded Targets(Y)

In [17]:
OHE_train_dataset[0]

(tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],
 
         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],
 
         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ...,

In [18]:
OHE_test_dataset[0]

(tensor([[[0.6196, 0.6235, 0.6471,  ..., 0.5373, 0.4941, 0.4549],
          [0.5961, 0.5922, 0.6235,  ..., 0.5333, 0.4902, 0.4667],
          [0.5922, 0.5922, 0.6196,  ..., 0.5451, 0.5098, 0.4706],
          ...,
          [0.2667, 0.1647, 0.1216,  ..., 0.1490, 0.0510, 0.1569],
          [0.2392, 0.1922, 0.1373,  ..., 0.1020, 0.1137, 0.0784],
          [0.2118, 0.2196, 0.1765,  ..., 0.0941, 0.1333, 0.0824]],
 
         [[0.4392, 0.4353, 0.4549,  ..., 0.3725, 0.3569, 0.3333],
          [0.4392, 0.4314, 0.4471,  ..., 0.3725, 0.3569, 0.3451],
          [0.4314, 0.4275, 0.4353,  ..., 0.3843, 0.3725, 0.3490],
          ...,
          [0.4863, 0.3922, 0.3451,  ..., 0.3804, 0.2510, 0.3333],
          [0.4549, 0.4000, 0.3333,  ..., 0.3216, 0.3216, 0.2510],
          [0.4196, 0.4118, 0.3490,  ..., 0.3020, 0.3294, 0.2627]],
 
         [[0.1922, 0.1843, 0.2000,  ..., 0.1412, 0.1412, 0.1294],
          [0.2000, 0.1569, 0.1765,  ..., 0.1216, 0.1255, 0.1333],
          [0.1843, 0.1294, 0.1412,  ...,

In [37]:
len(OHE_train_dataset),len(OHE_test_dataset)

(50000, 10000)

### We can see in the Above Cells that we have Dataset Instances Containing One-Hot Encoded Target Labels.

# --------------------------------------------------------------------------------------------

# -->Converting the Pre-Built Dataset into DataLoaders

### We use `torch.utils.data.DataLoader` Class to create our own Instance of DataLoader which can be then used with PyTorch Model to Train it.

## For `torch.utils.data.DataLoader` Method:-

### < First Argument >:-It takes the dataset from which we want Our DataLoader to Load the Data.
### < Second Argument >(batch_size):It takes the Amount of Data Samples we want to Load Per Batch.(Default is 1)
### < Third Argument >(shuffle):-If True the data is Re-Shuffled at Every Epoch.(Default False)
### < Fouth Argument >(num_workers):-It the Takes the Number of subprocesses Used for Data Loading.If `num_worker` = 0 then it is a `Single DataProcessing` and if `num_worker` > 0 then it is a `Multi DataProcessing`.
### Other Arguments are used for Customizing the Multi-DataProcessing System of our DataLoader.This will be Covered in Advance Topics.

#### `torch.utils.data.DataLoader`:-[LINK](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader)

In [37]:
train_dataloader = th.utils.data.DataLoader(OHE_train_dataset,
                                            batch_size=32,
                                            shuffle=True,
                                            pin_memory=True)

test_dataloader = th.utils.data.DataLoader(OHE_test_dataset,
                                           shuffle=False,
                                           batch_size=32,
                                           pin_memory=True)

In [7]:
import os 

os.cpu_count()

12

In [35]:
next(iter(train_dataloader))

PicklingError: Can't pickle <function <lambda> at 0x0000022814A014E0>: attribute lookup <lambda> on __main__ failed

# --------------------------------------------------------------------------------------------

In [38]:
model_V0 = th.nn.Sequential(
                            th.nn.Conv2d(in_channels=3,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                            th.nn.ReLU(),
                            th.nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                            th.nn.ReLU(),
                            th.nn.MaxPool2d(kernel_size=2),
                            th.nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                            th.nn.ReLU(),
                            th.nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                            th.nn.ReLU(),
                            th.nn.MaxPool2d(kernel_size=2),
                            th.nn.Flatten(),
                            th.nn.Linear(in_features=250,out_features=10)
)

In [39]:
summary(model_V0,
        input_size=(1,3,32,32),
        verbose=1,
        col_names=["input_size","output_size","num_params","trainable"],
        row_settings=["var_names"],
        col_width=18);

Layer (type (var_name))                  Input Shape        Output Shape       Param #            Trainable
Sequential (Sequential)                  [1, 3, 32, 32]     [1, 10]            --                 True
├─Conv2d (0)                             [1, 3, 32, 32]     [1, 10, 30, 30]    280                True
├─ReLU (1)                               [1, 10, 30, 30]    [1, 10, 30, 30]    --                 --
├─Conv2d (2)                             [1, 10, 30, 30]    [1, 10, 28, 28]    910                True
├─ReLU (3)                               [1, 10, 28, 28]    [1, 10, 28, 28]    --                 --
├─MaxPool2d (4)                          [1, 10, 28, 28]    [1, 10, 14, 14]    --                 --
├─Conv2d (5)                             [1, 10, 14, 14]    [1, 10, 12, 12]    910                True
├─ReLU (6)                               [1, 10, 12, 12]    [1, 10, 12, 12]    --                 --
├─Conv2d (7)                             [1, 10, 12, 12]    [1, 10, 10, 10] 

In [40]:
loss_fn = th.nn.CrossEntropyLoss()

optimizer = th.optim.Adam(model_V0.parameters(),
                          lr=0.001)

In [41]:
def accuracy(y_pred,Y):
    correct = th.eq(y_pred,Y).sum().item()
    acc = (correct/len(y_pred))*100.0
    return acc

In [42]:
def save_model_weigths(MODEL,epoch,extra_name):
    main_path = os.path.join(SAVE_PATH,extra_name)
    if not os.path.exists(main_path):
        os.mkdir(main_path)

    main_path += f"\\_{epoch}"
    current_state = dict()
    for key,value in MODEL.state_dict().items():
        current_state[key] = value.clone()
    th.save(current_state,main_path)
    print(f"[INFO] Saved the Model Weights to {main_path}")

In [43]:
DEVICE

'cuda'

In [44]:
next(model_V0.parameters())

Parameter containing:
tensor([[[[ 0.1676,  0.1347,  0.0620],
          [ 0.1062, -0.1113, -0.0637],
          [-0.1759,  0.1330,  0.1854]],

         [[-0.0391,  0.1774,  0.0775],
          [ 0.1372,  0.1809,  0.1589],
          [-0.1665,  0.0698, -0.0296]],

         [[ 0.0924, -0.0896,  0.0463],
          [ 0.0670, -0.1357,  0.1191],
          [ 0.0663,  0.0438,  0.1648]]],


        [[[-0.1538,  0.1399,  0.0189],
          [ 0.0995, -0.1754, -0.0475],
          [-0.1756,  0.1567,  0.0754]],

         [[ 0.1157,  0.0457,  0.1894],
          [-0.0686,  0.0888, -0.0711],
          [ 0.0152,  0.1517, -0.1383]],

         [[ 0.0330, -0.1780,  0.0478],
          [ 0.0358, -0.0790,  0.0292],
          [-0.1642, -0.0130, -0.1827]]],


        [[[-0.0436,  0.1057,  0.1227],
          [-0.0063, -0.0010,  0.1828],
          [-0.1087,  0.1345, -0.1334]],

         [[-0.0233,  0.0064, -0.0364],
          [ 0.0605,  0.1169, -0.0118],
          [ 0.0859, -0.1736, -0.1781]],

         [[ 0.0541, -0

In [45]:
EPOCHS = 2
TRAIN_DL_LEN = len(train_dataloader)
TEST_DL_LEN = len(test_dataloader)

model_V0.to(DEVICE)
for epoch in range(EPOCHS):
    start = time.time()
    model_V0.train()
    epoch_train_loss = 0.0
    epoch_train_accuracy = 0.0
    for X,Y in train_dataloader:
        X = X.to(DEVICE)
        Y = Y.to(DEVICE)

        Y_logits = model_V0(X).squeeze()
        y_pred = th.argmax(th.softmax(Y_logits,1),1)
        y_true = th.argmax(Y,1)
        loss = loss_fn(Y_logits,Y)
        acc = accuracy(y_pred,y_true)

        epoch_train_accuracy += acc
        epoch_train_loss += loss

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    model_V0.eval()
    epoch_test_loss = 0.0
    epoch_test_accuracy = 0.0
    
    with th.no_grad():
        for X,Y in test_dataloader:
            X = X.to(DEVICE)
            Y = Y.to(DEVICE)

            Y_logits = model_V0(X).squeeze()

            y_pred = th.argmax(th.softmax(Y_logits,1),1)
            y_true = th.argmax(Y,1)
            loss = loss_fn(Y_logits,Y)
            acc = accuracy(y_pred,y_true)

            epoch_test_accuracy += acc
            epoch_test_loss += loss

    epoch_test_accuracy /= TEST_DL_LEN
    epoch_test_loss /= TEST_DL_LEN
    epoch_train_accuracy /= TRAIN_DL_LEN
    epoch_train_loss /= TRAIN_DL_LEN
    end = time.time()    
    print(f"Epoch {epoch}[{round(end-start,2)}]:- |Train Loss:- {epoch_train_loss:.2f} <--------> Train Accuracy:- {epoch_train_accuracy:.2f}|++++++++|Test Loss:- {epoch_test_loss:.2f} <--------> Test Accuracy :- {epoch_test_accuracy:.2f}|")
    #save_model_weigths(MODEL=model_V0,epoch=epoch,extra_name="model_V0")

Epoch 0[35.55]:- |Train Loss:- 1.74 <--------> Train Accuracy:- 36.44|++++++++|Test Loss:- 1.59 <--------> Test Accuracy :- 42.46|
Epoch 1[34.48]:- |Train Loss:- 1.52 <--------> Train Accuracy:- 44.66|++++++++|Test Loss:- 1.45 <--------> Test Accuracy :- 47.09|


In [ ]:
fg = train_dataset.targets

In [ ]:
fg = pd.Series(fg)

In [ ]:
fg.value_counts()

In [ ]:
train_dataset[0]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output=False)

OHE.fit(np.array(train_dataset.targets).reshape(-1,1))

In [ ]:
train_dataset1 = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                      train=True,
                                      download=True,
                                      transform=thv.transforms.Compose([thv.transforms.ToTensor()]),
                                      target_transform=thv.transforms.Lambda(lambda x:OHE.transform([[x]])))

test_dataset1 = thv.datasets.CIFAR10(root="E:\PyImage_ComputerVision\DeepLearningFrameWorks\Working Data\InputData\Pre-BuiltIn Datasets",
                                    train=False,
                                    download=True,
                                    transform=thv.transforms.Compose([thv.transforms.ToTensor()]))

In [ ]:
train_dataset[4]

In [46]:
len(train_dataloader)

1563

In [15]:
thv.__version__

'0.16.1'

In [16]:
th.__version__

'2.1.1'

In [46]:
import torchvision

In [ ]:
class OHE_transform(torchvision.transforms.Tr)