In [1]:
import cv2
import numpy as np
from scipy.spatial import distance as dist

In [2]:
hello1 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\Hello1.png")
hello2 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\Hello2.png")
hello3 = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\Hello3.png")

In [3]:
hello1.shape

(561, 500, 3)

In [4]:
hello2.shape

(549, 500, 3)

In [5]:
hello3.shape

(458, 500, 3)

In [6]:
cv2.imshow("Hello1",hello1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
points = [(73, 239), (356, 117), (475, 265), (187, 443)]

In [8]:
out = hello1.copy()
for pts in points:
    cv2.circle(out,pts,2,(255,0,0),-1)

cv2.imshow("Out",out)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
rect = [1,2,3,4]

In [14]:
np.argsort(pts[:, 0])

TypeError: tuple indices must be integers or slices, not tuple

In [65]:
pts = np.array(points)

In [16]:
pts

array([[ 73, 239],
       [356, 117],
       [475, 265],
       [187, 443]])

In [17]:
pts[:,0]

array([ 73, 356, 475, 187])

In [18]:
np.argsort(pts[:,0])

array([0, 3, 1, 2], dtype=int64)

In [19]:
fg = pts[np.argsort(pts[:,0])]

In [20]:
fg

array([[ 73, 239],
       [187, 443],
       [356, 117],
       [475, 265]])

In [21]:
left = fg[:2]
right = fg[2:]

In [22]:
left

array([[ 73, 239],
       [187, 443]])

In [23]:
right

array([[356, 117],
       [475, 265]])

In [24]:
left = left[np.argsort(left[:,1])]

In [25]:
left

array([[ 73, 239],
       [187, 443]])

In [26]:
tl = left[0]
bl = left[1]

In [27]:
tl

array([ 73, 239])

In [28]:
D = dist.cdist(tl[np.newaxis], right, "euclidean")[0]

In [29]:
D

array([308.17689725, 402.83991858])

In [30]:
tr,br = right[np.argsort(D)]

In [31]:
tr

array([356, 117])

In [32]:
br

array([475, 265])

In [33]:
def order_points(pts):
    # sort the points based on their x-coordinates
    xSorted = pts[np.argsort(pts[:, 0]), :]

    # grab the left-most and right-most points from the sorted
    # x-roodinate points
    leftMost = xSorted[:2, :]
    rightMost = xSorted[2:, :]

    # now, sort the left-most coordinates according to their
    # y-coordinates so we can grab the top-left and bottom-left
    # points, respectively
    leftMost = leftMost[np.argsort(leftMost[:, 1]), :]
    (tl, bl) = leftMost

    # now that we have the top-left coordinate, use it as an
    # anchor to calculate the Euclidean distance between the
    # top-left and right-most points; by the Pythagorean
    # theorem, the point with the largest distance will be
    # our bottom-right point
    D = dist.cdist(tl[np.newaxis], rightMost, "euclidean")[0]
    (br, tr) = rightMost[np.argsort(D)[::-1], :]

    # return the coordinates in top-left, top-right,
    # bottom-right, and bottom-left order
    return np.array([tl, tr, br, bl], dtype="int32")

In [34]:
rect

[1, 2, 3, 4]

In [35]:
pts

array([[ 73, 239],
       [356, 117],
       [475, 265],
       [187, 443]])

In [36]:
ord = order_points(pts)

In [37]:
ord

array([[ 73, 239],
       [356, 117],
       [475, 265],
       [187, 443]])

In [38]:
tl, tr, br, bl

(array([ 73, 239]), array([356, 117]), array([475, 265]), array([187, 443]))

In [39]:
out = hello1.copy()
for pts in ord:
    cv2.circle(out,pts,2,(255,0,0),-1)
    cv2.imshow("OUT",out)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [89]:
def mouse_callback(event,x,y,flags,params):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(f"({x},{y})")

In [92]:
cv2.imshow("out",image)
cv2.setMouseCallback("out",mouse_callback)
cv2.waitKey(0)
cv2.destroyAllWindows()

(64,71)
(273,62)
(10,342)
(344,329)


In [42]:
pts1 = np.array([(72,238),(355,115),(123,233),(115,315)])

In [43]:
ord1 = order_points(pts1)

In [48]:
out = hello1.copy()
for pts in ord1:
    cv2.circle(out,pts,2,(255,0,0),-1)
    cv2.imshow("OUT",out)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [49]:
np.argsort(pts1[:,0])

array([0, 3, 2, 1], dtype=int64)

In [50]:
tl, tr, br, bl

(array([ 73, 239]), array([356, 117]), array([475, 265]), array([187, 443]))

In [51]:
ord

array([[ 73, 239],
       [356, 117],
       [475, 265],
       [187, 443]])

In [52]:
w1 = np.sqrt(((ord[0][0] - ord[1][0])**2) + ((ord[0][1] - ord[1][1])**2))
w2 = np.sqrt(((ord[2][0] - ord[3][0])**2) + ((ord[2][1] - ord[3][1])**2))

In [53]:
w1

308.1768972522113

In [54]:
w2

338.5675708038205

In [55]:
mxw = max(int(w1),int(w2))

In [56]:
mxw

338

In [57]:
tl, tr, br, bl

(array([ 73, 239]), array([356, 117]), array([475, 265]), array([187, 443]))

In [58]:
h1 = np.sqrt(((ord[1][0] - ord[2][0])**2) + ((ord[1][1] - ord[2][1])**2))
h2 = np.sqrt(((ord[0][0] - ord[3][0])**2) + ((ord[0][1] - ord[3][1])**2))

In [59]:
h1

189.90787240133042

In [60]:
h2

233.69210512980536

In [61]:
mxh = max(int(h1),int(h2))

In [62]:
mxh

233

In [63]:
def four_point_transform(pts):
    # obtain a consistent order of the points and unpack them
    # individually
    rect = order_points(pts)
    (tl, tr, br, bl) = rect

    # compute the width of the new image, which will be the
    # maximum distance between bottom-right and bottom-left
    # x-coordiates or the top-right and top-left x-coordinates
    widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
    widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
    maxWidth = max(int(widthA), int(widthB))

    # compute the height of the new image, which will be the
    # maximum distance between the top-right and bottom-right
    # y-coordinates or the top-left and bottom-left y-coordinates
    heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
    heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
    maxHeight = max(int(heightA), int(heightB))

    print(maxWidth,maxHeight)
    # now that we have the dimensions of the new image, construct
    # the set of destination points to obtain a "birds eye view",
    # (i.e. top-down view) of the image, again specifying points
    # in the top-left, top-right, bottom-right, and bottom-left
    # order
    dst = np.array([
        [0, 0],
        [maxWidth - 1, 0],
        [maxWidth - 1, maxHeight - 1],
        [0, maxHeight - 1]], dtype="float32")

    # compute the perspective transform matrix and then apply it
    M = cv2.getPerspectiveTransform(rect, dst)
    warped = cv2.warpPerspective(image, M, (maxWidth, maxHeight))

    # return the warped image
    return warped

In [66]:
four_point_transform(pts)

338 233


In [67]:
pts

array([[ 73, 239],
       [356, 117],
       [475, 265],
       [187, 443]])

In [68]:
ord = np.array(ord,dtype=np.float32)

In [69]:
ord

array([[ 73., 239.],
       [356., 117.],
       [475., 265.],
       [187., 443.]], dtype=float32)

In [70]:
dst = np.array([[0,0],
       [mxw-1,0],
       [mxw-1,mxh-1],
       [0,mxh-1]],dtype=np.float32)

In [71]:
dst

array([[  0.,   0.],
       [337.,   0.],
       [337., 232.],
       [  0., 232.]], dtype=float32)

In [72]:
M = cv2.getPerspectiveTransform(ord,dst)

In [73]:
wrap = cv2.warpPerspective(hello1,M,(mxw,mxh))

In [74]:
wrap.shape

(233, 338, 3)

In [75]:
cv2.imshow("Hello",hello1)
cv2.imshow("Wrapeed",wrap)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [76]:
wrap = cv2.warpPerspective(hello1,M,(600,600))

In [77]:
wrap.shape

(600, 600, 3)

In [78]:
cv2.imshow("Hello",hello1)
cv2.imshow("Wrapeed",wrap)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [81]:
import math
import cv2
import scipy.spatial.distance
import numpy as np

img = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\Hello1.png")
(rows,cols,_) = img.shape

#image center
u0 = (cols)/2.0
v0 = (rows)/2.0

#detected corners on the original image
p = [[73, 239],[356, 117],[475, 265],[187, 443]]

#widths and heights of the projected image
w1 = scipy.spatial.distance.euclidean(p[0],p[1])
w2 = scipy.spatial.distance.euclidean(p[2],p[3])

h1 = scipy.spatial.distance.euclidean(p[0],p[3])
h2 = scipy.spatial.distance.euclidean(p[1],p[2])

w = max(w1,w2)
h = max(h1,h2)
print(w,h)

#visible aspect ratio
ar_vis = float(w)/float(h)

#make numpy arrays and append 1 for linear algebra
m1 = np.array((p[0][0],p[0][1],1)).astype('float32')
m2 = np.array((p[1][0],p[1][1],1)).astype('float32')
m3 = np.array((p[2][0],p[2][1],1)).astype('float32')
m4 = np.array((p[3][0],p[3][1],1)).astype('float32')

#calculate the focal disrance
k2 = np.dot(np.cross(m1,m4),m3) / np.dot(np.cross(m2,m4),m3)
k3 = np.dot(np.cross(m1,m4),m2) / np.dot(np.cross(m3,m4),m2)

n2 = k2 * m2 - m1
n3 = k3 * m3 - m1

n21 = n2[0]
n22 = n2[1]
n23 = n2[2]

n31 = n3[0]
n32 = n3[1]
n33 = n3[2]

f = math.sqrt(np.abs( (1.0/(n23*n33)) * ((n21*n31 - (n21*n33 + n23*n31)*u0 + n23*n33*u0*u0) + (n22*n32 - (n22*n33+n23*n32)*v0 + n23*n33*v0*v0))))

A = np.array([[f,0,u0],[0,f,v0],[0,0,1]]).astype('float32')

At = np.transpose(A)
Ati = np.linalg.inv(At)
Ai = np.linalg.inv(A)

#calculate the real aspect ratio
ar_real = math.sqrt(np.dot(np.dot(np.dot(n2,Ati),Ai),n2)/np.dot(np.dot(np.dot(n3,Ati),Ai),n3))

if ar_real < ar_vis:
    W = int(w)
    H = int(W / ar_real)
else:
    H = int(h)
    W = int(ar_real * H)

pts1 = np.array(p).astype('float32')
pts2 = np.float32([[0,0],[W,0],[0,H],[W,H]])

#project the image with the new w/h
M = cv2.getPerspectiveTransform(pts1,pts2)

dst = cv2.warpPerspective(img,M,(W,H))

cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

338.5675708038205 233.69210512980536


"\n#calculate the focal disrance\nk2 = np.dot(np.cross(m1,m4),m3) / np.dot(np.cross(m2,m4),m3)\nk3 = np.dot(np.cross(m1,m4),m2) / np.dot(np.cross(m3,m4),m2)\n\nn2 = k2 * m2 - m1\nn3 = k3 * m3 - m1\n\nn21 = n2[0]\nn22 = n2[1]\nn23 = n2[2]\n\nn31 = n3[0]\nn32 = n3[1]\nn33 = n3[2]\n\nf = math.sqrt(np.abs( (1.0/(n23*n33)) * ((n21*n31 - (n21*n33 + n23*n31)*u0 + n23*n33*u0*u0) + (n22*n32 - (n22*n33+n23*n32)*v0 + n23*n33*v0*v0))))\n\nA = np.array([[f,0,u0],[0,f,v0],[0,0,1]]).astype('float32')\n\nAt = np.transpose(A)\nAti = np.linalg.inv(At)\nAi = np.linalg.inv(A)\n\n#calculate the real aspect ratio\nar_real = math.sqrt(np.dot(np.dot(np.dot(n2,Ati),Ai),n2)/np.dot(np.dot(np.dot(n3,Ati),Ai),n3))\n\nif ar_real < ar_vis:\n    W = int(w)\n    H = int(W / ar_real)\nelse:\n    H = int(h)\n    W = int(ar_real * H)\n\npts1 = np.array(p).astype('float32')\npts2 = np.float32([[0,0],[W,0],[0,H],[W,H]])\n\n#project the image with the new w/h\nM = cv2.getPerspectiveTransform(pts1,pts2)\n\ndst = cv2.warpPers

In [82]:
m1

array([ 73., 239.,   1.], dtype=float32)

In [83]:
m2

array([356., 117.,   1.], dtype=float32)

In [84]:
m3

array([475., 265.,   1.], dtype=float32)

In [85]:
m4

array([187., 443.,   1.], dtype=float32)

In [91]:
image = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\book.png")

In [93]:
points = [(64,71),(273,62),(10,342),(344,329)]

In [102]:
def order_points(pts):
    # sort the points based on their x-coordinates
    xSorted = pts[np.argsort(pts[:, 0]), :]

    # grab the left-most and right-most points from the sorted
    # x-roodinate points
    leftMost = xSorted[:2, :]
    rightMost = xSorted[2:, :]

    # now, sort the left-most coordinates according to their
    # y-coordinates so we can grab the top-left and bottom-left
    # points, respectively
    leftMost = leftMost[np.argsort(leftMost[:, 1]), :]
    (tl, bl) = leftMost

    # now that we have the top-left coordinate, use it as an
    # anchor to calculate the Euclidean distance between the
    # top-left and right-most points; by the Pythagorean
    # theorem, the point with the largest distance will be
    # our bottom-right point
    D = dist.cdist(tl[np.newaxis], rightMost, "euclidean")[0]
    (br, tr) = rightMost[np.argsort(D)[::-1], :]

    # return the coordinates in top-left, top-right,
    # bottom-right, and bottom-left order
    return np.array([tl, tr, br, bl], dtype="float32")

In [106]:
def four_point_transform(pts):
    # obtain a consistent order of the points and unpack them
    # individually
    rect = order_points(pts)
    (tl, tr, br, bl) = rect

    # compute the width of the new image, which will be the
    # maximum distance between bottom-right and bottom-left
    # x-coordiates or the top-right and top-left x-coordinates
    widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
    widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
    maxWidth = max(int(widthA), int(widthB))

    # compute the height of the new image, which will be the
    # maximum distance between the top-right and bottom-right
    # y-coordinates or the top-left and bottom-left y-coordinates
    heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
    heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
    maxHeight = max(int(heightA), int(heightB))
    # now that we have the dimensions of the new image, construct
    # the set of destination points to obtain a "birds eye view",
    # (i.e. top-down view) of the image, again specifying points
    # in the top-left, top-right, bottom-right, and bottom-left
    # order
    dst = np.array([
        [0, 0],
        [maxWidth - 1, 0],
        [maxWidth - 1, maxHeight - 1],
        [0, maxHeight - 1]], dtype=np.float32)
    # compute the perspective transform matrix and then apply it
    M = cv2.getPerspectiveTransform(rect,dst)
    warped = cv2.warpPerspective(image, M, (maxWidth, maxHeight))

    # return the warped image
    return warped

In [115]:
import math
import cv2
import scipy.spatial.distance
import numpy as np

img = cv2.imread(r"E:\PyImage_ComputerVision\OpenCVBasic\WorkingData\InputData\book.png")
(rows,cols,_) = img.shape

#image center
u0 = (cols)/2.0
v0 = (rows)/2.0

#detected corners on the original image
p = []
p.append((67,71))
p.append((273,62))
p.append((10,342))
p.append((344,329))

#widths and heights of the projected image
w1 = scipy.spatial.distance.euclidean(p[0],p[1])
w2 = scipy.spatial.distance.euclidean(p[2],p[3])

h1 = scipy.spatial.distance.euclidean(p[0],p[2])
h2 = scipy.spatial.distance.euclidean(p[1],p[3])

w = max(w1,w2)
h = max(h1,h2)

#visible aspect ratio
ar_vis = float(w)/float(h)

#make numpy arrays and append 1 for linear algebra
m1 = np.array((p[0][0],p[0][1],1)).astype('float32')
m2 = np.array((p[1][0],p[1][1],1)).astype('float32')
m3 = np.array((p[2][0],p[2][1],1)).astype('float32')
m4 = np.array((p[3][0],p[3][1],1)).astype('float32')

#calculate the focal disrance
k2 = np.dot(np.cross(m1,m4),m3) / np.dot(np.cross(m2,m4),m3)
k3 = np.dot(np.cross(m1,m4),m2) / np.dot(np.cross(m3,m4),m2)

n2 = k2 * m2 - m1
n3 = k3 * m3 - m1

n21 = n2[0]
n22 = n2[1]
n23 = n2[2]

n31 = n3[0]
n32 = n3[1]
n33 = n3[2]

f = math.sqrt(np.abs( (1.0/(n23*n33)) * ((n21*n31 - (n21*n33 + n23*n31)*u0 + n23*n33*u0*u0) + (n22*n32 - (n22*n33+n23*n32)*v0 + n23*n33*v0*v0))))

A = np.array([[f,0,u0],[0,f,v0],[0,0,1]]).astype('float32')

At = np.transpose(A)
Ati = np.linalg.inv(At)
Ai = np.linalg.inv(A)

#calculate the real aspect ratio
ar_real = math.sqrt(np.dot(np.dot(np.dot(n2,Ati),Ai),n2)/np.dot(np.dot(np.dot(n3,Ati),Ai),n3))

if ar_real < ar_vis:
    W = int(w)
    H = int(W / ar_real)
else:
    H = int(h)
    W = int(ar_real * H)

pts1 = np.array(p).astype('float32')
pts2 = np.float32([[0,0],[W,0],[0,H],[W,H]])

#project the image with the new w/h
M = cv2.getPerspectiveTransform(pts1,pts2)

dst = cv2.warpPerspective(img,M,(W,H))

In [107]:
wrap = four_point_transform(np.array(points))

In [116]:
cv2.imshow("Normal Image",image)
cv2.imshow("Output1",wrap)
cv2.imshow("Output2",dst)

cv2.waitKey(0)
cv2.destroyAllWindows()