In [1]:
import torch as th
from torch import nn
import numpy as np
import torchvision as thv
import time

In [2]:
DEVICE = "cuda" if th.cuda.is_available() else "cpu"
DEVICE

'cuda'

In [3]:
thv.__version__

'0.16.0'

In [4]:
th.__version__

'2.1.0'

In [5]:
train_dataset = thv.datasets.CIFAR10(root="E:\PyTorch\Working Data\Input Data",
                                     train=True,
                                     download=True,
                                     transform=thv.transforms.ToTensor())

Files already downloaded and verified


In [6]:
test_dataset = thv.datasets.CIFAR10(root="E:\PyTorch\Working Data\Input Data",
                                    train=False,
                                    download=True,
                                    transform=thv.transforms.ToTensor())

Files already downloaded and verified


In [7]:
len(train_dataset)

50000

In [8]:
train_dataset[0]

(tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],
 
         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],
 
         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ...,

In [9]:
len(test_dataset)

10000

In [10]:
test_dataset[0]

(tensor([[[0.6196, 0.6235, 0.6471,  ..., 0.5373, 0.4941, 0.4549],
          [0.5961, 0.5922, 0.6235,  ..., 0.5333, 0.4902, 0.4667],
          [0.5922, 0.5922, 0.6196,  ..., 0.5451, 0.5098, 0.4706],
          ...,
          [0.2667, 0.1647, 0.1216,  ..., 0.1490, 0.0510, 0.1569],
          [0.2392, 0.1922, 0.1373,  ..., 0.1020, 0.1137, 0.0784],
          [0.2118, 0.2196, 0.1765,  ..., 0.0941, 0.1333, 0.0824]],
 
         [[0.4392, 0.4353, 0.4549,  ..., 0.3725, 0.3569, 0.3333],
          [0.4392, 0.4314, 0.4471,  ..., 0.3725, 0.3569, 0.3451],
          [0.4314, 0.4275, 0.4353,  ..., 0.3843, 0.3725, 0.3490],
          ...,
          [0.4863, 0.3922, 0.3451,  ..., 0.3804, 0.2510, 0.3333],
          [0.4549, 0.4000, 0.3333,  ..., 0.3216, 0.3216, 0.2510],
          [0.4196, 0.4118, 0.3490,  ..., 0.3020, 0.3294, 0.2627]],
 
         [[0.1922, 0.1843, 0.2000,  ..., 0.1412, 0.1412, 0.1294],
          [0.2000, 0.1569, 0.1765,  ..., 0.1216, 0.1255, 0.1333],
          [0.1843, 0.1294, 0.1412,  ...,

In [11]:
X_train = [x for x,y in train_dataset]

In [12]:
Y_train = [[y] for x,y in train_dataset]

In [13]:
X_test = [x for x,y in test_dataset]

In [14]:
Y_test = [[y] for x,y in test_dataset]

In [15]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output=False)

Y_main_train = OHE.fit_transform(Y_train)
Y_main_test = OHE.transform(Y_test)

In [16]:
Y_main_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [17]:
Y_main_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [18]:
Y_main_train.shape

(50000, 10)

In [19]:
Y_main_test.shape

(10000, 10)

In [20]:
X_train_tensor = th.Tensor(np.array(X_train))
Y_train_tensor = th.Tensor(Y_main_train)
X_test_tensor = th.Tensor(np.array(X_test))
Y_test_tensor = th.Tensor(Y_main_test)

In [21]:
X_train_tensor.shape

torch.Size([50000, 3, 32, 32])

In [22]:
X_train_tensor.dtype

torch.float32

In [23]:
Y_train_tensor.shape

torch.Size([50000, 10])

In [24]:
Y_train_tensor.dtype

torch.float32

In [25]:
X_test_tensor.shape

torch.Size([10000, 3, 32, 32])

In [26]:
X_test_tensor.dtype

torch.float32

In [27]:
Y_test_tensor.shape

torch.Size([10000, 10])

In [28]:
Y_test_tensor.dtype

torch.float32

In [29]:
train_main_dataset = th.utils.data.TensorDataset(X_train_tensor,Y_train_tensor)

In [30]:
len(train_main_dataset)

50000

In [31]:
train_main_dataset[0]

(tensor([[[0.2314, 0.1686, 0.1961,  ..., 0.6196, 0.5961, 0.5804],
          [0.0627, 0.0000, 0.0706,  ..., 0.4824, 0.4667, 0.4784],
          [0.0980, 0.0627, 0.1922,  ..., 0.4627, 0.4706, 0.4275],
          ...,
          [0.8157, 0.7882, 0.7765,  ..., 0.6275, 0.2196, 0.2078],
          [0.7059, 0.6784, 0.7294,  ..., 0.7216, 0.3804, 0.3255],
          [0.6941, 0.6588, 0.7020,  ..., 0.8471, 0.5922, 0.4824]],
 
         [[0.2431, 0.1804, 0.1882,  ..., 0.5176, 0.4902, 0.4863],
          [0.0784, 0.0000, 0.0314,  ..., 0.3451, 0.3255, 0.3412],
          [0.0941, 0.0275, 0.1059,  ..., 0.3294, 0.3294, 0.2863],
          ...,
          [0.6667, 0.6000, 0.6314,  ..., 0.5216, 0.1216, 0.1333],
          [0.5451, 0.4824, 0.5647,  ..., 0.5804, 0.2431, 0.2078],
          [0.5647, 0.5059, 0.5569,  ..., 0.7216, 0.4627, 0.3608]],
 
         [[0.2471, 0.1765, 0.1686,  ..., 0.4235, 0.4000, 0.4039],
          [0.0784, 0.0000, 0.0000,  ..., 0.2157, 0.1961, 0.2235],
          [0.0824, 0.0000, 0.0314,  ...,

In [32]:
test_main_dataset = th.utils.data.TensorDataset(X_test_tensor,Y_test_tensor)

In [33]:
len(test_main_dataset)

10000

In [34]:
test_main_dataset[0]

(tensor([[[0.6196, 0.6235, 0.6471,  ..., 0.5373, 0.4941, 0.4549],
          [0.5961, 0.5922, 0.6235,  ..., 0.5333, 0.4902, 0.4667],
          [0.5922, 0.5922, 0.6196,  ..., 0.5451, 0.5098, 0.4706],
          ...,
          [0.2667, 0.1647, 0.1216,  ..., 0.1490, 0.0510, 0.1569],
          [0.2392, 0.1922, 0.1373,  ..., 0.1020, 0.1137, 0.0784],
          [0.2118, 0.2196, 0.1765,  ..., 0.0941, 0.1333, 0.0824]],
 
         [[0.4392, 0.4353, 0.4549,  ..., 0.3725, 0.3569, 0.3333],
          [0.4392, 0.4314, 0.4471,  ..., 0.3725, 0.3569, 0.3451],
          [0.4314, 0.4275, 0.4353,  ..., 0.3843, 0.3725, 0.3490],
          ...,
          [0.4863, 0.3922, 0.3451,  ..., 0.3804, 0.2510, 0.3333],
          [0.4549, 0.4000, 0.3333,  ..., 0.3216, 0.3216, 0.2510],
          [0.4196, 0.4118, 0.3490,  ..., 0.3020, 0.3294, 0.2627]],
 
         [[0.1922, 0.1843, 0.2000,  ..., 0.1412, 0.1412, 0.1294],
          [0.2000, 0.1569, 0.1765,  ..., 0.1216, 0.1255, 0.1333],
          [0.1843, 0.1294, 0.1412,  ...,

In [35]:
train_dataloader = th.utils.data.DataLoader(train_main_dataset,
                                            batch_size=32,
                                            shuffle=True)

In [36]:
test_dataloader = th.utils.data.DataLoader(test_main_dataset,
                                           batch_size=32, 
                                           shuffle=False)

In [37]:
len(train_dataloader)

1563

In [38]:
1563*32

50016

In [39]:
len(test_dataloader)

313

In [40]:
313*32

10016

In [63]:
model = nn.Sequential(
                        nn.Conv2d(in_channels=3,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                        nn.ReLU(),
                        nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                        nn.ReLU(),
                        nn.MaxPool2d(kernel_size=2),
                        nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                        nn.ReLU(),
                        nn.Conv2d(in_channels=10,out_channels=10,kernel_size=3,stride=1,padding="valid"),
                        nn.ReLU(),
                        nn.MaxPool2d(kernel_size=2),
                        nn.Flatten(),
                        nn.Linear(in_features=250,out_features=10)
)

In [64]:
model

Sequential(
  (0): Conv2d(3, 10, kernel_size=(3, 3), stride=(1, 1), padding=valid)
  (1): ReLU()
  (2): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1), padding=valid)
  (3): ReLU()
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1), padding=valid)
  (6): ReLU()
  (7): Conv2d(10, 10, kernel_size=(3, 3), stride=(1, 1), padding=valid)
  (8): ReLU()
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Flatten(start_dim=1, end_dim=-1)
  (11): Linear(in_features=250, out_features=10, bias=True)
)

In [65]:
trainable_params = sum(
    p.numel() for p in model.parameters()
)
trainable_params

5520

In [66]:
loss_fn = nn.CrossEntropyLoss()

optimizer = th.optim.Adam(model.parameters(),
                          lr=0.001)

In [67]:
def accuracy(Y_pred,Y_true):
    correct = th.eq(Y_pred,Y_true).sum().item()
    acc = (correct/len(Y_pred))*100
    return acc

In [68]:
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter()

In [69]:
from torch.utils.tensorboard import SummaryWriter

writer1 = SummaryWriter(log_dir="abc")

In [70]:
writer2 = SummaryWriter(log_dir="abcdefg\\ab\\bcd")

In [61]:
TRAIN_DL_LEN = len(train_dataloader)
TEST_DL_LEN = len(test_dataloader)
EPOCHS = 20

model.to(DEVICE)
for epoch in range(EPOCHS):
    start = time.time()
    model.train()
    epoch_train_loss = 0.0
    epoch_train_accuracy = 0.0
    for X,Y in train_dataloader:
        X = X.to(DEVICE)
        Y = Y.to(DEVICE)
        
        Y_logits = model(X).squeeze()
        Y_true = th.argmax(Y,1)
        Y_pred = th.argmax(th.softmax(Y_logits,1),1)
        
        loss = loss_fn(Y_logits,Y)
        acc = accuracy(Y_pred,Y_true)
        
        epoch_train_loss += loss
        epoch_train_accuracy += acc
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    model.eval()
    epoch_test_loss = 0.0
    epoch_test_accuracy = 0.0
    with th.no_grad():
        for X,Y in test_dataloader:
            X = X.to(DEVICE)
            Y = Y.to(DEVICE)
            
            Y_logits = model(X).squeeze()
            Y_true = th.argmax(Y,1)
            Y_pred = th.argmax(th.softmax(Y_logits,1),1)
            
            loss = loss_fn(Y_logits,Y)
            acc = accuracy(Y_pred,Y_true)
            
            epoch_test_accuracy += acc
            epoch_test_loss += loss
            
    
    epoch_train_accuracy /= TRAIN_DL_LEN
    epoch_train_loss /= TRAIN_DL_LEN
    epoch_test_accuracy /= TEST_DL_LEN
    epoch_test_loss /= TEST_DL_LEN
    end=time.time()
    
    
    writer.add_scalars(main_tag="Loss",tag_scalar_dict={"Train Loss":epoch_train_loss,"Test Loss":epoch_test_loss},global_step=epoch)
    writer.add_scalars(main_tag="Accuracy",tag_scalar_dict={"Train Accuracy":epoch_train_accuracy,"Test Accuracy":epoch_test_accuracy},global_step=epoch)
    print(f"Epoch {epoch}[{round(end-start,2)}] :- |Train Loss:- {epoch_train_loss:.2f} <--------> Train Accuracy:- {epoch_train_accuracy:.2f}|++++++++|Test Loss:- {epoch_test_loss:.2f} <--------> Test Accuracy :- {epoch_test_accuracy:.2f}|")

Epoch 0[4.7] :- |Train Loss:- 1.74 <--------> Train Accuracy:- 36.68|++++++++|Test Loss:- 1.54 <--------> Test Accuracy :- 44.64|
Epoch 1[4.5] :- |Train Loss:- 1.48 <--------> Train Accuracy:- 46.82|++++++++|Test Loss:- 1.42 <--------> Test Accuracy :- 49.06|
Epoch 2[4.95] :- |Train Loss:- 1.40 <--------> Train Accuracy:- 49.87|++++++++|Test Loss:- 1.35 <--------> Test Accuracy :- 51.14|
Epoch 3[4.63] :- |Train Loss:- 1.34 <--------> Train Accuracy:- 52.01|++++++++|Test Loss:- 1.34 <--------> Test Accuracy :- 51.92|
Epoch 4[4.54] :- |Train Loss:- 1.30 <--------> Train Accuracy:- 53.80|++++++++|Test Loss:- 1.26 <--------> Test Accuracy :- 55.47|
Epoch 5[4.54] :- |Train Loss:- 1.25 <--------> Train Accuracy:- 55.93|++++++++|Test Loss:- 1.27 <--------> Test Accuracy :- 54.66|
Epoch 6[4.55] :- |Train Loss:- 1.21 <--------> Train Accuracy:- 57.22|++++++++|Test Loss:- 1.19 <--------> Test Accuracy :- 57.43|
Epoch 7[4.55] :- |Train Loss:- 1.18 <--------> Train Accuracy:- 58.67|++++++++|Test L

In [71]:
TRAIN_DL_LEN = len(train_dataloader)
TEST_DL_LEN = len(test_dataloader)
EPOCHS = 20

model.to(DEVICE)
for epoch in range(EPOCHS):
    start = time.time()
    model.train()
    epoch_train_loss = 0.0
    epoch_train_accuracy = 0.0
    for X,Y in train_dataloader:
        X = X.to(DEVICE)
        Y = Y.to(DEVICE)
        
        Y_logits = model(X).squeeze()
        Y_true = th.argmax(Y,1)
        Y_pred = th.argmax(th.softmax(Y_logits,1),1)
        
        loss = loss_fn(Y_logits,Y)
        acc = accuracy(Y_pred,Y_true)
        
        epoch_train_loss += loss
        epoch_train_accuracy += acc
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    model.eval()
    epoch_test_loss = 0.0
    epoch_test_accuracy = 0.0
    with th.no_grad():
        for X,Y in test_dataloader:
            X = X.to(DEVICE)
            Y = Y.to(DEVICE)
            
            Y_logits = model(X).squeeze()
            Y_true = th.argmax(Y,1)
            Y_pred = th.argmax(th.softmax(Y_logits,1),1)
            
            loss = loss_fn(Y_logits,Y)
            acc = accuracy(Y_pred,Y_true)
            
            epoch_test_accuracy += acc
            epoch_test_loss += loss
            
    
    epoch_train_accuracy /= TRAIN_DL_LEN
    epoch_train_loss /= TRAIN_DL_LEN
    epoch_test_accuracy /= TEST_DL_LEN
    epoch_test_loss /= TEST_DL_LEN
    end=time.time()
    
    
    writer1.add_scalar(tag="Train Loss",scalar_value=epoch_train_loss,global_step=epoch)
    writer1.add_scalar(tag="Test Loss",scalar_value=epoch_test_loss,global_step=epoch)
    writer1.add_scalar(tag="Train Accuracy",scalar_value=epoch_train_accuracy,global_step=epoch)
    writer1.add_scalar(tag="Test Accuracy",scalar_value=epoch_test_accuracy,global_step=epoch)
    print(f"Epoch {epoch}[{round(end-start,2)}] :- |Train Loss:- {epoch_train_loss:.2f} <--------> Train Accuracy:- {epoch_train_accuracy:.2f}|++++++++|Test Loss:- {epoch_test_loss:.2f} <--------> Test Accuracy :- {epoch_test_accuracy:.2f}|")

Epoch 0[4.49] :- |Train Loss:- 1.78 <--------> Train Accuracy:- 35.40|++++++++|Test Loss:- 1.60 <--------> Test Accuracy :- 41.85|
Epoch 1[4.37] :- |Train Loss:- 1.53 <--------> Train Accuracy:- 45.23|++++++++|Test Loss:- 1.48 <--------> Test Accuracy :- 46.52|
Epoch 2[4.32] :- |Train Loss:- 1.42 <--------> Train Accuracy:- 49.53|++++++++|Test Loss:- 1.38 <--------> Test Accuracy :- 50.34|
Epoch 3[4.33] :- |Train Loss:- 1.35 <--------> Train Accuracy:- 52.06|++++++++|Test Loss:- 1.35 <--------> Test Accuracy :- 50.56|
Epoch 4[4.34] :- |Train Loss:- 1.29 <--------> Train Accuracy:- 54.10|++++++++|Test Loss:- 1.30 <--------> Test Accuracy :- 54.07|
Epoch 5[4.33] :- |Train Loss:- 1.26 <--------> Train Accuracy:- 55.53|++++++++|Test Loss:- 1.26 <--------> Test Accuracy :- 54.99|
Epoch 6[4.32] :- |Train Loss:- 1.23 <--------> Train Accuracy:- 56.61|++++++++|Test Loss:- 1.24 <--------> Test Accuracy :- 55.28|
Epoch 7[4.32] :- |Train Loss:- 1.20 <--------> Train Accuracy:- 57.75|++++++++|Test

In [72]:
%tensorboard --logdir abc