In [29]:
import numpy as np

In [33]:
np.random.seed(100)
c = np.random.rand(2,4,5)
c

array([[[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
        [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
        [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
        [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375]],

       [[0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
        [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497],
        [0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606],
        [0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ]]])

In [34]:
c.transpose((0,2))

ValueError: axes don't match array

In [30]:
a =np.array([1,2,3,4])

In [32]:
a1= a.reshape(-1)
a1

array([1, 2, 3, 4])

In [36]:
a = np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [58]:
a = np.arange(40,step=5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
b =np.array([[1,2,3],
             [11,22,33]])

In [6]:
type(b)

numpy.ndarray

In [7]:
c = np.array([[[1,2,3],
               [4,5,6]],
               [[7,8,9],
                [10,11,12]],
                [[11,12,13],
                [14,15,16]]])

In [8]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [11]:
c.ndim

3

In [12]:
a.shape

(4,)

In [13]:
b.shape

(2, 3)

In [14]:
c.shape

(3, 2, 3)

In [15]:
np.array?

In [16]:
import pandas as pd

In [17]:
pa = pd.DataFrame(a)

In [18]:
pa

0
0  1
1  2
2  3
3  4

In [19]:
pb = pd.DataFrame(b)

In [20]:
pb

0   1   2
0   1   2   3
1  11  22  33

In [24]:
pc =pd.DataFrame(c)

ValueError: Must pass 2-d input. shape=(3, 2, 3)

In [27]:
np.ones?

In [17]:
ones1 = np.ones((3,6))

In [18]:
ones1

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
ones2 = np.ones((4,6),dtype = np.int32)

In [20]:
ones2

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## Find the Difference between C style and Fortan Style

In [24]:
ones3 = np.ones((3,6,6),order = 'F')

In [25]:
ones3

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
ones4 = np.ones((3,6),order = "C")

In [29]:
ones4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
zero1 = np.zeros((3,4))

In [22]:
zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
zero2 = np.zeros((2,5),dtype='bool')

In [24]:
zero2

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [25]:
zero2.dtype

dtype('bool')

## New Thing


In [86]:
np.arange?

In [26]:
ara1 = np.arange(5.0,dtype="i")

In [27]:
ara1

array([0, 1, 2, 3, 4], dtype=int32)

In [28]:
ara2 = np.arange(stop = -5,step =-1,dtype= "i")

In [29]:
ara2

array([ 0, -1, -2, -3, -4], dtype=int32)

In [30]:
ara3 = np.arange(start=1,stop=7.0,step=0.5)

In [31]:
ara3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [32]:
ara4 = np.arange(start=2.0,stop=7.0,step=1)

In [33]:
ara4

array([2., 3., 4., 5., 6.])

In [34]:
ara5 = np.arange(start=-9,stop =-0.9,step=1)

In [35]:
ara5

array([-9., -8., -7., -6., -5., -4., -3., -2., -1.])

In [36]:
ara6 = np.arange(start=-9,stop=9,step=1.5,dtype="i")

In [37]:
ara6

array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9, 11, 13], dtype=int32)

In [38]:
ara7 = np.arange(start=0.1,stop=1.3,step=0.2)

In [39]:
ara7

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1])

In [40]:
np.arange(start=0, stop=5, step=0.5, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Errors are in np.arange so we should use linespace for real value steps


In [87]:
np.linspace?

In [39]:
a1 = np.linspace(start=1,stop=20,num=20)
a1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [23]:
a2 = np.linspace(start=1,stop=20,num=20,dtype=np.int32,retstep=True)
a2

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 1.0)

In [43]:
a3 = np.linspace(start=2.5,stop=20.0,num=5)
a3

array([ 2.5  ,  6.875, 11.25 , 15.625, 20.   ])

In [20]:
a4 = np.linspace(start=-1,stop=-10,num=20)
a4
type(a4)

numpy.ndarray

In [49]:
a5 = np.linspace(start=67,stop=65,num=5)
a5

array([67. , 66.5, 66. , 65.5, 65. ])

In [51]:
a6 = np.linspace(start=50,stop=60,num=3.4)

TypeError: 'float' object cannot be interpreted as an integer

In [55]:
a7 = np.linspace(start=1,stop=25,num=4,retstep=True)
a7

(array([ 1.,  9., 17., 25.]), 8.0)

In [16]:
a8 = np.linspace(start=[1,9,2],stop=[25,90,30],num=10,axis=0)
a8

array([[ 1.        ,  9.        ,  2.        ],
       [ 3.66666667, 18.        ,  5.11111111],
       [ 6.33333333, 27.        ,  8.22222222],
       [ 9.        , 36.        , 11.33333333],
       [11.66666667, 45.        , 14.44444444],
       [14.33333333, 54.        , 17.55555556],
       [17.        , 63.        , 20.66666667],
       [19.66666667, 72.        , 23.77777778],
       [22.33333333, 81.        , 26.88888889],
       [25.        , 90.        , 30.        ]])

In [19]:
a9 = np.linspace(start=[[1,2,3],[4,5,6]],stop=[[10,20,30],[40,50,60]],num=10)
a9

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 2.,  4.,  6.],
        [ 8., 10., 12.]],

       [[ 3.,  6.,  9.],
        [12., 15., 18.]],

       [[ 4.,  8., 12.],
        [16., 20., 24.]],

       [[ 5., 10., 15.],
        [20., 25., 30.]],

       [[ 6., 12., 18.],
        [24., 30., 36.]],

       [[ 7., 14., 21.],
        [28., 35., 42.]],

       [[ 8., 16., 24.],
        [32., 40., 48.]],

       [[ 9., 18., 27.],
        [36., 45., 54.]],

       [[10., 20., 30.],
        [40., 50., 60.]]])

In [28]:
a

NameError: name 'a' is not defined

## Random Numbers

In [72]:
np.random.randint?

In [52]:
rar1 = np.random.randint(0,5,size=(2,3,4))

In [53]:
rar1

array([[[0, 2, 4, 1],
        [4, 4, 2, 1],
        [3, 4, 0, 0]],

       [[4, 1, 3, 4],
        [1, 3, 1, 1],
        [1, 0, 2, 4]]])

In [54]:
rar2 = np.random.randint(3,size=(4,8))

In [55]:
rar2

array([[2, 1, 2, 2, 1, 2, 0, 0],
       [2, 1, 1, 0, 2, 2, 2, 2],
       [2, 0, 1, 1, 1, 1, 0, 1],
       [0, 1, 2, 0, 0, 0, 2, 1]])

In [57]:
rar3 = np.random.randint(-3,0,size=10)

In [58]:
rar3

array([-2, -3, -2, -2, -3, -1, -2, -3, -2, -2])

In [21]:
rar4 = np.random.randint(-4,size=10)

ValueError: high <= 0

In [23]:
rar4 = np.random.randint(0,10,size=(2,6),dtype=np.float32)

TypeError: Unsupported dtype dtype('float32') for randint

In [24]:
rar5 = np.random.randint(0,1,size=10)

In [63]:
rar5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
rar6 = np.random.randint(-8,-4,size=(2,5))

In [65]:
rar6

array([[-8, -8, -5, -6, -6],
       [-5, -6, -7, -8, -5]])

In [34]:
nar7 = np.random.randint(low=[1,2,3],high=7,size=[3,7])
nar7

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 2 with shape (3, 7).

In [33]:
nar8 = np.random.randint([1,2,3,4,5],20)

In [74]:
nar8

array([18, 10,  7, 17, 12])

In [76]:
nar8 = np.random.randint([1,10,25,2,3,4,5,6],30)

In [77]:
nar8

array([ 7, 17, 25, 26, 11, 15, 28, 25])

In [83]:
nar9 = np.random.randint(0,[11,12,33,4,55])

In [84]:
nar9

array([ 9,  0, 26,  1, 11])

## its not fully complete we can use braodcasting in random.randint

# Using random.random

In [26]:
np.random.random?

In [27]:
ran1 = np.random.random((2,3))

In [87]:
ran1

array([[0.94890741, 0.85744814, 0.42849487],
       [0.76474449, 0.04334231, 0.83112802]])

In [88]:
ran1 = np.random.random()

In [89]:
ran1

0.7509293388688143

# Using random.rand

In [25]:
np.random.rand?

In [94]:
nar2 = np.random.rand(2,3,4)

In [95]:
nar2

array([[[0.1545313 , 0.41871332, 0.07525094, 0.60072039],
        [0.67347028, 0.96724128, 0.78619603, 0.76031284],
        [0.73332202, 0.03112371, 0.76556701, 0.6821802 ]],

       [[0.01321485, 0.57118721, 0.3573134 , 0.74340464],
        [0.10639457, 0.03723897, 0.7800595 , 0.52789508],
        [0.26816535, 0.48320485, 0.34266374, 0.98176713]]])

In [96]:
nar3 = np.random.rand(3,5)

In [97]:
nar3

array([[0.59415825, 0.79122291, 0.65584005, 0.19113742, 0.05240118],
       [0.49868955, 0.22021824, 0.82448034, 0.33757047, 0.68664085],
       [0.83651414, 0.16421433, 0.35293593, 0.21490465, 0.2995127 ]])

In [98]:
nar4 = np.random.rand((1,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [99]:
tup1= (2,5)

In [101]:
nar5 =np.random.rand(tup1)

TypeError: 'tuple' object cannot be interpreted as an integer

In [102]:
nar6 = np.random.rand(*tup1)

In [103]:
nar6

array([[0.90313195, 0.93436694, 0.25811345, 0.85331154, 0.84676496],
       [0.04882641, 0.21150082, 0.75786589, 0.61722718, 0.33126491]])

# USing random.seed

In [113]:
np.random.seed(7)
ara1 = np.random.randint(0,10,size=10)
ara1

array([4, 9, 6, 3, 3, 7, 7, 9, 7, 8])

In [117]:
ara2 = np.random.rand(2,5)
ara2

array([[0.95791373, 0.17957689, 0.14271575, 0.0835081 , 0.54723513],
       [0.31020924, 0.28271973, 0.92099354, 0.43334216, 0.41875723]])

In [120]:
np.random.seed(seed=7)
ara3 = np.random.randint(0,10,size=10)
ara3

array([4, 9, 6, 3, 3, 7, 7, 9, 7, 8])

In [125]:
np.random.seed(seed=11)
ara10 = np.random.randint(0,5,size=10)
ara11 = np.random.rand(1,4)
ara12 = np.random.random((2,4))

In [126]:
ara10

array([1, 0, 3, 1, 4, 1, 2, 0, 4, 0])

In [127]:
ara11

array([[0.82618135, 0.09281249, 0.88970819, 0.71376193]])

In [128]:
ara12

array([[0.51789854, 0.78538872, 0.58766585, 0.73683621],
       [0.67251024, 0.97007099, 0.98857911, 0.7781032 ]])

In [129]:
np.random.seed(seed=11)
ara13 = np.random.randint(0,5,size=10)
ara14 = np.random.rand(1,4)
ara15 = np.random.random((2,4))

In [130]:
ara13

array([1, 0, 3, 1, 4, 1, 2, 0, 4, 0])

In [131]:
ara14

array([[0.82618135, 0.09281249, 0.88970819, 0.71376193]])

In [132]:
ara15

array([[0.51789854, 0.78538872, 0.58766585, 0.73683621],
       [0.67251024, 0.97007099, 0.98857911, 0.7781032 ]])

# Viewing  Arrays



## Acessing Elements of the array

In [134]:
a

array([1, 2, 3, 4])

In [137]:
a[1]

2

In [138]:
a[0]

1

In [139]:
a[3]

4

In [140]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [135]:
b

array([[ 1,  2,  3],
       [11, 22, 33]])

In [141]:
b[0][0]

1

In [142]:
b[0,0]

1

In [143]:
b[1,0,2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [144]:
b[2,4]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [136]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [146]:
c[1,1,0]

10

In [147]:
c[1][1][0]

10

In [148]:
c[2,3,4]

IndexError: index 3 is out of bounds for axis 1 with size 2

In [149]:
c[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [150]:
b[0]

array([1, 2, 3])

In [151]:
c[1][0,1]

8

In [152]:
c[1][1,0]

10

## Slicing With Indexes

In [154]:
a

array([1, 2, 3, 4])

In [155]:
a[1:4]

array([2, 3, 4])

In [157]:
a[:3]

array([1, 2, 3])

In [158]:
a[2:]

array([3, 4])

In [156]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [159]:
c[1,1:,:]

array([[10, 11, 12]])

In [160]:
d = np.random.randint(0,20,size=(4,6,7,4))

In [161]:
d

array([[[[ 0, 15,  0,  6],
         [11, 10, 12, 14],
         [ 7, 15,  0,  8],
         [16,  5,  7, 18],
         [ 3,  1, 16,  3],
         [ 8, 17,  4,  8],
         [18,  0, 14, 19]],

        [[ 6, 17, 11, 18],
         [16, 10, 15, 14],
         [ 0, 12,  8,  8],
         [ 4,  1,  1,  9],
         [11,  2,  8, 19],
         [ 0, 18, 18, 13],
         [ 8,  6,  7,  2]],

        [[ 4,  4, 13,  1],
         [10, 17, 15, 17],
         [ 4, 10, 14,  7],
         [ 3,  3,  3, 17],
         [ 6,  8, 17,  1],
         [ 7,  4,  8,  5],
         [ 5, 18, 15, 10]],

        [[ 0, 17, 16, 11],
         [12,  4,  2,  4],
         [12,  2, 17, 17],
         [12,  1, 19,  3],
         [14,  2, 19, 19],
         [18, 16, 11, 18],
         [19, 15,  0, 11]],

        [[19, 18,  9,  7],
         [13,  2, 12, 13],
         [18, 10, 10, 17],
         [17, 12, 11, 11],
         [17, 17,  6, 18],
         [ 1,  6,  9, 18],
         [14, 15, 15,  3]],

        [[ 4,  5, 19,  1],
         [10, 12, 

In [162]:
d[2:5,1:3,2:4,1:7]

array([[[[ 3,  2, 18],
         [ 6, 13,  1]],

        [[ 5,  6,  3],
         [ 4, 14,  6]]],


       [[[10, 18,  9],
         [10,  8, 10]],

        [[11,  2, 14],
         [ 0, 12,  3]]]])

In [163]:
d[:,:,:,:4]

array([[[[ 0, 15,  0,  6],
         [11, 10, 12, 14],
         [ 7, 15,  0,  8],
         [16,  5,  7, 18],
         [ 3,  1, 16,  3],
         [ 8, 17,  4,  8],
         [18,  0, 14, 19]],

        [[ 6, 17, 11, 18],
         [16, 10, 15, 14],
         [ 0, 12,  8,  8],
         [ 4,  1,  1,  9],
         [11,  2,  8, 19],
         [ 0, 18, 18, 13],
         [ 8,  6,  7,  2]],

        [[ 4,  4, 13,  1],
         [10, 17, 15, 17],
         [ 4, 10, 14,  7],
         [ 3,  3,  3, 17],
         [ 6,  8, 17,  1],
         [ 7,  4,  8,  5],
         [ 5, 18, 15, 10]],

        [[ 0, 17, 16, 11],
         [12,  4,  2,  4],
         [12,  2, 17, 17],
         [12,  1, 19,  3],
         [14,  2, 19, 19],
         [18, 16, 11, 18],
         [19, 15,  0, 11]],

        [[19, 18,  9,  7],
         [13,  2, 12, 13],
         [18, 10, 10, 17],
         [17, 12, 11, 11],
         [17, 17,  6, 18],
         [ 1,  6,  9, 18],
         [14, 15, 15,  3]],

        [[ 4,  5, 19,  1],
         [10, 12, 

# Manuplating Arrays

## Arthematic Operations!

In [164]:
a

array([1, 2, 3, 4])

In [166]:
a1 = np.array([2,4,6,8])
a2 = np.array([1,3,5,7,9])

In [167]:
a1

array([2, 4, 6, 8])

In [168]:
a2

array([1, 3, 5, 7, 9])

In [170]:
fg1 = a + a1
fg1

array([ 3,  6,  9, 12])

In [171]:
fg2 = a + a2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [173]:
fg3 = a + 1
fg3

array([2, 3, 4, 5])

In [176]:
fg4 = a + a1 + 3
fg4

array([ 6,  9, 12, 15])

In [177]:
np.add?

In [182]:
fga = np.add(a1,a)
fga

array([ 3,  6,  9, 12])

In [184]:
fg5 = a-a1
fg5

array([-1, -2, -3, -4])

In [185]:
fg6 = a2 - a

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [187]:
fg7 = a1 - a
fg7

array([1, 2, 3, 4])

In [189]:
fg8 = a1 * a
fg8

array([ 2,  8, 18, 32])

In [191]:
fg9 = a1 / a
fg9

array([2., 2., 2., 2.])

In [193]:
fg10 = a1 % a 
fg10

array([0, 0, 0, 0])

In [200]:
fg1

array([ 3,  6,  9, 12])

In [201]:
a

array([1, 2, 3, 4])

In [202]:
np.lcm(a,fg1)

array([ 3,  6,  9, 12])

In [209]:
np.reciprocal(a2,dtype=np.float32)

array([1.        , 0.33333334, 0.2       , 0.14285715, 0.11111111],
      dtype=float32)

### We can find all the mathematical functions in https://numpy.org/doc/stable/reference/generated/numpy.modf.html

## Practincing BROADCASTING

In [210]:
a

array([1, 2, 3, 4])

In [211]:
b 

array([[ 1,  2,  3],
       [11, 22, 33]])

In [212]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [216]:
fga = a * b

ValueError: operands could not be broadcast together with shapes (4,) (2,3) 

In [220]:
b1 = np.random.randint(0,10,size=(6,8))
b1

array([[6, 5, 9, 6, 6, 3, 5, 8],
       [5, 3, 4, 9, 6, 7, 8, 5],
       [1, 0, 6, 8, 5, 1, 0, 7],
       [3, 3, 5, 4, 7, 8, 8, 7],
       [0, 1, 8, 1, 1, 7, 5, 9],
       [4, 5, 6, 8, 7, 5, 1, 0]])

In [223]:
fga = a * c

ValueError: operands could not be broadcast together with shapes (4,) (3,2,3) 

In [233]:
a1 = np.random.randint(0,10,size=5)
a2 = np.random.randint(0,10,size=(10,5))

In [234]:
a1

array([7, 3, 2, 2, 5])

In [235]:
a2

array([[1, 2, 4, 1, 9],
       [0, 5, 3, 2, 1],
       [6, 3, 7, 8, 4],
       [0, 2, 4, 7, 5],
       [9, 4, 1, 5, 9],
       [8, 9, 6, 6, 1],
       [8, 9, 1, 8, 7],
       [7, 8, 3, 2, 3],
       [0, 6, 3, 9, 9],
       [8, 1, 2, 4, 9]])

In [236]:
fga = a2 * a1

In [237]:
fga

array([[ 7,  6,  8,  2, 45],
       [ 0, 15,  6,  4,  5],
       [42,  9, 14, 16, 20],
       [ 0,  6,  8, 14, 25],
       [63, 12,  2, 10, 45],
       [56, 27, 12, 12,  5],
       [56, 27,  2, 16, 35],
       [49, 24,  6,  4, 15],
       [ 0, 18,  6, 18, 45],
       [56,  3,  4,  8, 45]])

In [242]:
c1 = np.random.randint(0,10,size=(3,2,5))

In [243]:
c1

array([[[4, 8, 6, 7, 7],
        [1, 9, 6, 4, 8]],

       [[2, 7, 8, 2, 7],
        [3, 8, 3, 0, 2]],

       [[5, 3, 1, 1, 9],
        [3, 3, 2, 1, 2]]])

In [246]:
a1

array([7, 3, 2, 2, 5])

In [249]:
fgc = c1 + a1
fgc

array([[[11, 11,  8,  9, 12],
        [ 8, 12,  8,  6, 13]],

       [[ 9, 10, 10,  4, 12],
        [10, 11,  5,  2,  7]],

       [[12,  6,  3,  3, 14],
        [10,  6,  4,  3,  7]]])

In [251]:
b1 = np.random.randint(0,10,size=(2,5))
b1

array([[2, 4, 8, 9, 7],
       [0, 7, 9, 4, 6]])

In [252]:
c1

array([[[4, 8, 6, 7, 7],
        [1, 9, 6, 4, 8]],

       [[2, 7, 8, 2, 7],
        [3, 8, 3, 0, 2]],

       [[5, 3, 1, 1, 9],
        [3, 3, 2, 1, 2]]])

In [255]:
fgbc = c1 + b1
fgbc

array([[[ 6, 12, 14, 16, 14],
        [ 1, 16, 15,  8, 14]],

       [[ 4, 11, 16, 11, 14],
        [ 3, 15, 12,  4,  8]],

       [[ 7,  7,  9, 10, 16],
        [ 3, 10, 11,  5,  8]]])

In [256]:
c1

array([[[4, 8, 6, 7, 7],
        [1, 9, 6, 4, 8]],

       [[2, 7, 8, 2, 7],
        [3, 8, 3, 0, 2]],

       [[5, 3, 1, 1, 9],
        [3, 3, 2, 1, 2]]])

In [258]:
b2 = np.random.randint(0,10,size=(1,5))
b2

array([[1, 3, 0, 5, 1]])

In [261]:
fgz = c1 + b2
fgz

array([[[ 5, 11,  6, 12,  8],
        [ 2, 12,  6,  9,  9]],

       [[ 3, 10,  8,  7,  8],
        [ 4, 11,  3,  5,  3]],

       [[ 6,  6,  1,  6, 10],
        [ 4,  6,  2,  6,  3]]])

In [262]:
y = np.random.randint(0,10,size=(4,1))
z = np.random.randint(0,10,size=7)

In [263]:
y

array([[3],
       [0],
       [5],
       [1]])

In [264]:
z

array([9, 7, 3, 1, 8, 6, 0])

In [266]:
fgzy =z * y
fgzy

array([[27, 21,  9,  3, 24, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [45, 35, 15,  5, 40, 30,  0],
       [ 9,  7,  3,  1,  8,  6,  0]])

In [267]:
z1 = np.random.randint(0,10,size=(3,5,1))

In [268]:
z1

array([[[2],
        [3],
        [0],
        [0],
        [4]],

       [[1],
        [0],
        [3],
        [8],
        [7]],

       [[8],
        [9],
        [4],
        [5],
        [2]]])

In [272]:
z

array([9, 7, 3, 1, 8, 6, 0])

In [274]:
fg1 =  z *z1
fg1

array([[[18, 14,  6,  2, 16, 12,  0],
        [27, 21,  9,  3, 24, 18,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [36, 28, 12,  4, 32, 24,  0]],

       [[ 9,  7,  3,  1,  8,  6,  0],
        [ 0,  0,  0,  0,  0,  0,  0],
        [27, 21,  9,  3, 24, 18,  0],
        [72, 56, 24,  8, 64, 48,  0],
        [63, 49, 21,  7, 56, 42,  0]],

       [[72, 56, 24,  8, 64, 48,  0],
        [81, 63, 27,  9, 72, 54,  0],
        [36, 28, 12,  4, 32, 24,  0],
        [45, 35, 15,  5, 40, 30,  0],
        [18, 14,  6,  2, 16, 12,  0]]])

In [275]:
z1

array([[[2],
        [3],
        [0],
        [0],
        [4]],

       [[1],
        [0],
        [3],
        [8],
        [7]],

       [[8],
        [9],
        [4],
        [5],
        [2]]])

In [276]:
y

array([[3],
       [0],
       [5],
       [1]])

In [279]:
fg2 = z1 * y
fg2

ValueError: operands could not be broadcast together with shapes (3,5,1) (4,1) 

## Rules to BroadCasting :- https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcastable-arrays

# AGGREGATION

In [280]:
np.sum?

In [283]:
b1 = np.random.randint(0,10,size = (4,8))
b1

array([[3, 8, 1, 1, 6, 2, 0, 0],
       [9, 0, 1, 7, 9, 1, 2, 5],
       [7, 8, 4, 7, 7, 6, 1, 4],
       [0, 1, 8, 6, 7, 3, 9, 2]])

In [284]:
np.sum(b1)

135

In [285]:
np.sum(b1,axis=0)

array([19, 17, 14, 21, 29, 12, 12, 11])

In [287]:
np.sum(b1,axis=1)

array([21, 34, 44, 36])

In [297]:
c1 = np.random.randint(0,10,size=(4,5,8))
c1

array([[[5, 7, 6, 1, 8, 1, 6, 9],
        [0, 9, 0, 9, 1, 1, 6, 7],
        [4, 1, 2, 0, 4, 4, 9, 3],
        [9, 2, 7, 4, 5, 6, 8, 6],
        [0, 2, 0, 7, 2, 8, 0, 4]],

       [[9, 5, 9, 5, 4, 1, 7, 7],
        [7, 3, 5, 0, 5, 5, 9, 6],
        [9, 2, 7, 0, 9, 3, 3, 1],
        [0, 3, 8, 1, 9, 3, 8, 0],
        [9, 9, 5, 5, 1, 4, 1, 5]],

       [[0, 4, 1, 4, 2, 2, 1, 3],
        [5, 9, 9, 0, 2, 0, 9, 9],
        [8, 4, 3, 6, 7, 8, 3, 3],
        [6, 9, 9, 2, 2, 9, 6, 4],
        [8, 3, 0, 9, 8, 8, 2, 5]],

       [[9, 4, 4, 6, 9, 4, 4, 1],
        [8, 5, 8, 9, 0, 9, 1, 0],
        [2, 8, 1, 5, 6, 8, 7, 3],
        [8, 5, 5, 2, 6, 3, 5, 7],
        [9, 2, 3, 4, 0, 6, 2, 4]]])

In [305]:
np.sum(c1,axis=0)

array([[23, 20, 20, 16, 23,  8, 18, 20],
       [20, 26, 22, 18,  8, 15, 25, 22],
       [23, 15, 13, 11, 26, 23, 22, 10],
       [23, 19, 29,  9, 22, 21, 27, 17],
       [26, 16,  8, 25, 11, 26,  5, 18]])

In [306]:
np.sum(c1,axis=1)

array([[18, 21, 15, 21, 20, 20, 29, 29],
       [34, 22, 34, 11, 28, 16, 28, 19],
       [27, 29, 22, 21, 21, 27, 21, 24],
       [36, 24, 21, 26, 21, 30, 19, 15]])

In [307]:
np.sum(c1,axis=2)

array([[43, 33, 27, 47, 23],
       [47, 40, 34, 32, 39],
       [17, 43, 42, 47, 43],
       [41, 40, 40, 41, 30]])

In [310]:
np.max?

In [309]:
np.amax?

In [312]:
np.std?

In [313]:
np.var?

## All the Other Available Aggrigation functions are in the above documentaiton link as arthematic operations
